"use client";
import {useEffect,useState} from "react";
import {Activity,ShieldCheck,FlaskConical,TrendingUp} from "lucide-react";
import AppShell from "@/components/AppShell";
import {deriveTradingLabState} from "@/lib/v65/trading-state";
import MetricInfo from "@/components/v65/MetricInfo";

type EvalRow={symbol:string;action:string;status:string;reason:string;riskCode?:string|null;evaluatedAt?:string|null;orderStatus?:string|null;fillStatus?:string|null;fillPrice?:number|null;realizedPnl?:number|null;returnPct?:number|null;quoteProvider?:string|null;quoteAgeSeconds?:number|null;marketSession?:string|null;integrityState?:string|null;disagreementPct?:number|null;automatic?:boolean};
const when=(x?:string|null)=>x?new Date(x).toLocaleString():"—";
const money=(x?:number|null,signed=true)=>x==null?"—":`${signed?(x>=0?"+":"-"):""}$${Math.abs(x).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function TradingLab(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;const load=()=>fetch("/api/trading-lab/status",{cache:"no-store"}).then(r=>r.json()).then(x=>{if(live)setData(x)}).finally(()=>{if(live)setLoading(false)});load();const timer=setInterval(load,15000);return()=>{live=false;clearInterval(timer)}},[]);
 const m=data?.metrics||{},rows:EvalRow[]=data?.recentEvaluations||[];
 const lab=deriveTradingLabState({brokerConnected:Boolean(data?.broker?.connected),lastRunAt:data?.runner?.lastAutomaticRun||null,evaluated:Number(data?.funnel?.evaluated||0),orders:Number(data?.orders||0),fills:Number(m?.trades||0),maturedOutcomes:Number(data?.learning?.maturedOutcomes||0)});
 return <AppShell><section className="tradingLabPage v65TradingLab">
  <div className="tradingLabHead"><div><div className="eyebrow">NIVORA TRADING LAB · PAPER</div><h1>Prove the edge before risking capital.</h1><p>Trading Lab converts frozen NIVORA decisions into risk-gated paper orders, records every outcome, and measures whether the strategy actually adds value.</p></div><div className="paperBadge"><FlaskConical size={17}/> PAPER ONLY</div></div>
  <div className="v65TradingStateGrid">
   <article><small>EXECUTION STATE <MetricInfo title="Execution state">Broker connectivity, evaluated signals, actual paper orders and fills are separate states. CONNECTED alone does not mean NIVORA traded.</MetricInfo></small><b>{lab.executionLabel}</b><span>{lab.nextStep}</span></article>
   <article><small>LEARNING STATE <MetricInfo title="Learning state">NIVORA is allowed to say it is learning only when version-matched decisions have matured outcomes. Production weights are never silently rewritten.</MetricInfo></small><b>{lab.learningLabel}</b><span>{data?.learning?.reason||"Waiting for matured outcomes."}</span></article>
   <article><small>MATURED OUTCOMES</small><b>{data?.learning?.maturedOutcomes??0}</b><span>Version-matched observations eligible for calibration.</span></article>
   <article><small>USER APPROVAL</small><b>PAPER AUTO</b><span>Paper orders use simulated money and do not prompt for approval. Live-money execution is disabled.</span></article>
  </div>
  <div className="tradingLabSafety"><ShieldCheck size={18}/><div><b>Automatic PAPER execution — no approval prompt by design</b><span>NIVORA itself must produce BUY/ADD/TRIM/SELL. The runner then validates quote integrity and risk before sending an Alpaca PAPER order. HOLD/WAIT correctly create no order. Live-money auto execution remains disabled.</span></div></div>
  <div className="tradingLabMethod"><Activity size={18}/><div><b>AUTOMATIC RUNNER</b><p>{data?.runner?.automatic?"ON":"OFF"} · {data?.runner?.scheduler||"Scheduler"} · {data?.runner?.schedule||"—"} · Market: {data?.runner?.marketSession||"—"} · Last run: {when(data?.runner?.lastAutomaticRun)} · {data?.runner?.lastRunOk===true?"HEALTHY":data?.runner?.lastRunOk===false?"ERROR":"WAITING"}</p></div><TrendingUp size={18}/></div>
  <div className="v63SignalLegend"><span><b>BUY / ADD</b> opens or increases paper risk only after all gates pass.</span><span><b>SELL / TRIM</b> only reduces an existing paper position; it cannot open a short.</span><span><b>HOLD / WAIT / AVOID</b> intentionally creates no order.</span></div>
  {loading?<div className="tradingLabEmpty">Loading Trading Lab…</div>:<><div className="tradingLabGrid">
   <article><small>PAPER BROKER <MetricInfo title="Paper broker">Shows whether NIVORA can read the Alpaca Paper account. Connected means API connectivity only—not that an order has been sent.</MetricInfo></small><b>{data?.broker?.connected?"CONNECTED":data?.broker?.configured?"UNREACHABLE":"NOT CONFIGURED"}</b><span>{data?.broker?.connected?`Alpaca Paper · equity ${money(Number(data?.broker?.equity||0),false)} · ${data?.broker?.positions??0} positions`:data?.broker?.error||"Paper broker credentials not configured"}</span></article>
   <article><small>PAPER ORDERS <MetricInfo title="Paper orders">Count of paper broker orders recorded by Trading Lab. Orders are distinct from fills and from evaluated signals.</MetricInfo></small><b>{data?.orders??0}</b><span>{data?.lastOrder?.at?`Last ${data.lastOrder.symbol||""} · ${data.lastOrder.status||""} · ${when(data.lastOrder.at)}`:"No broker orders recorded yet"}</span></article>
   <article><small>WIN RATE <MetricInfo title="Win rate">Percentage of matured realized paper trades with positive P&amp;L. Hidden until actual trades exist.</MetricInfo></small><b>{m.trades?`${m.winRatePct}%`:"Collecting"}</b><span>{m.wins??0} wins · {m.losses??0} losses</span></article>
   <article><small>PROFIT FACTOR <MetricInfo title="Profit factor">Gross realized paper wins divided by gross realized paper losses. A useful execution metric only after enough trades exist.</MetricInfo></small><b>{m.profitFactor??"Collecting"}</b><span>Gross wins ÷ gross losses</span></article>
  </div><div className="tradingLabGrid secondary">
   <article><small>NET PAPER P&amp;L <MetricInfo title="Net paper P&L">Realized simulated profit/loss from Alpaca Paper fills. It is not live-money performance.</MetricInfo></small><b>{m.trades?money(Number(m.netPnl||0)):"—"}</b><span>Realized paper results only</span></article>
   <article><small>EXPECTANCY / TRADE <MetricInfo title="Expectancy per trade">Average realized paper P&amp;L per completed trade.</MetricInfo></small><b>{m.trades?money(Number(m.expectancy||0)):"—"}</b><span>Average realized paper P&L</span></article>
   <article><small>AVG ALPHA <MetricInfo title="Average alpha">Paper trade return minus the matched benchmark return over the same measurement window.</MetricInfo></small><b>{m.trades?`${m.averageAlphaPct}%`:"—"}</b><span>Trade return minus benchmark return</span></article>
   <article><small>MAX DRAWDOWN <MetricInfo title="Maximum drawdown">Largest observed decline in the realized paper-trade equity sequence. It is sample-dependent and stays blank without trades.</MetricInfo></small><b>{m.trades?`$${Math.abs(Number(m.maxDrawdownDollars||0)).toLocaleString()}`:"—"}</b><span>Observed realized-trade curve</span></article>
  </div>
  <section className="v65DecisionAudit"><div className="tradingAuditHead"><div><small>REAL-MARKET DECISION AUDIT</small><h2>Is NIVORA actually finding BUYs?</h2></div><span>Latest decision per analyzed ticker</span></div>
   <div className="v65AuditGrid">
    <article><small>ANALYZED</small><b>{data?.decisionAudit?.total??0}</b><span>Unique tickers on the current engine</span></article>
    <article><small>BUY SIGNALS</small><b>{data?.decisionAudit?.actions?.BUY??0}</b><span>{data?.decisionAudit?.total?`${(((data?.decisionAudit?.actions?.BUY??0)/data.decisionAudit.total)*100).toFixed(1)}% of analyzed tickers`:"No decision snapshots yet"}</span></article>
    <article><small>DOMINANT BLOCKER</small><b>{data?.decisionAudit?.dominantBlockers?.[0]?.count??0}</b><span>{data?.decisionAudit?.dominantBlockers?.[0]?.reason||"Waiting for real decisions"}</span></article>
    <article><small>CLOSEST TO BUY</small><b>{data?.decisionAudit?.closestToBuy?.[0]?.symbol||"—"}</b><span>{data?.decisionAudit?.closestToBuy?.[0]?`${String(data.decisionAudit.closestToBuy[0].closestPath||"").replaceAll("_"," ")} · ${data.decisionAudit.closestToBuy[0].primaryBlocker||"one gate remains"}`:"No near-BUY candidate yet"}</span></article>
   </div>
   {data?.decisionAudit?.closestToBuy?.length?<div className="v65ClosestList">{data.decisionAudit.closestToBuy.slice(0,5).map((x:any)=><span key={x.symbol}><b>{x.symbol}</b><em>{String(x.closestPath||"").replaceAll("_"," ")}</em><small>{x.primaryBlocker||"—"}</small></span>)}</div>:null}
  </section>
  <div className="tradingLabMethod"><Activity size={18}/><div><b>DECISION FUNNEL</b><p>{data?.funnel?.snapshots??0} snapshots → {data?.funnel?.evaluated??0} evaluated → {data?.funnel?.intents??0} intents → {data?.funnel?.authorized??0} authorized → {data?.funnel?.submitted??0} submitted · {data?.funnel?.blocked??0} blocked.</p></div><TrendingUp size={18}/></div>
  <section className="v65RunAudit"><div className="tradingAuditHead"><div><small>RECENT AUTOMATIC CYCLES</small><h2>What the scheduler actually ran</h2></div><span>{data?.recentRuns?.length??0} recent runs</span></div>
   {Array.isArray(data?.recentRuns)&&data.recentRuns.length?<div className="v65RunList">{data.recentRuns.slice(0,8).map((r:any)=><div key={r.id}><span><b>{r.status}</b><small>{r.session||"—"} · {r.automatic?"AUTO":"MANUAL"}</small></span><span><b>{r.processed??0}</b><small>processed</small></span><span><b>{r.submitted??0}</b><small>submitted</small></span><span><b>{r.blocked??0}</b><small>blocked</small></span><span><b>{r.errors??0}</b><small>errors</small></span><span><b>{when(r.started_at)}</b><small>{r.error||"No runner error"}</small></span></div>)}</div>:<div className="tradingLabEmpty">No run records yet. Deploy the V65 trading-runs migration and let the GitHub paper workflow run once.</div>}
  </section>
  {data?.runAuditStatus==="migration-required"&&<div className="tradingLabSafety"><ShieldCheck size={18}/><div><b>V65 run-audit migration required</b><span>Run supabase/20260904_v65_trading_runs.sql once, then refresh. Paper trading can still use the existing V61 tables, but NIVORA cannot show run-by-run proof until this table exists.</span></div></div>}
  {data?.auditStatus&&data.auditStatus!=="ready"&&<div className="tradingLabSafety"><ShieldCheck size={18}/><div><b>Trading audit migration required</b><span>Run supabase/20260901_nivora_v61_trading_lab_console.sql in Supabase, then refresh this page.</span></div></div>}
  <section className="tradingAudit"><div className="tradingAuditHead"><div><small>RECENT DECISIONS</small><h2>What Trading Lab actually did</h2></div><span>Auto-refreshes every 15s</span></div>{rows.length?<div className="tradingAuditTable"><div className="tradingAuditRow head"><span>Symbol</span><span>Today</span><span>Result</span><span>Risk / Order</span><span>Reason</span><span>Time</span></div>{rows.map((r,i)=><div className="tradingAuditRow" key={`${r.symbol}-${r.evaluatedAt}-${i}`}><b>{r.symbol}</b><span className={`auditAction ${String(r.action||"").toLowerCase().replaceAll(" ","-")}`}>{r.action}</span><span className={`auditStatus ${String(r.status||"").toLowerCase()}`}>{r.status}</span><span title={r.quoteProvider?`${r.quoteProvider} · ${r.quoteAgeSeconds??"?"}s · ${r.marketSession||""} · ${r.integrityState||"integrity unknown"}${r.disagreementPct!=null?` · gap ${r.disagreementPct}%`:""}`:""}>{r.fillStatus?`${r.fillStatus}${r.realizedPnl!=null?` · ${money(r.realizedPnl)}`:""}`:r.orderStatus||r.riskCode||r.integrityState||"—"}</span><span>{r.reason}</span><span>{when(r.evaluatedAt)}</span></div>)}</div>:<div className="tradingLabEmpty">No evaluated paper decisions yet. Run the paper cycle after fresh NIVORA snapshots are available.</div>}</section>
  <div className="tradingLabMethod"><ShieldCheck size={18}/><div><b>PAPER BROKER PROOF</b><p>Read-only Alpaca connectivity is checked on this page. For a one-time order-path proof, enable TRADING_LAB_SELF_TEST_ORDER_ENABLED and run the GitHub workflow “NIVORA Paper Broker Self Test”. It submits a deliberately non-marketable PAPER limit order and immediately cancels it. This diagnostic is never treated as a NIVORA signal.</p></div><span>{data?.selfTest?.orderEnabled?"ARMED":"DISARMED"}</span></div>
  <div className="tradingLabMethod"><Activity size={18}/><div><b>How a paper order reaches the broker</b><p>NIVORA decision → Trade Intent → fresh quote → portfolio/daily-loss/spread/gap/duplicate gates → protected limit order → Alpaca Paper → fill reconciliation → P&L and alpha.</p></div><TrendingUp size={18}/></div></>}
 </section></AppShell>
}
