create table if not exists public.nivora_portfolio_snapshots (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 as_of timestamptz not null default now(),
 snapshot_day date not null default current_date,
 total_value numeric not null,
 spy_price numeric,
 qqq_price numeric,
 holdings jsonb not null default '[]'::jsonb,
 engine_version text not null default 'v65.11',
 created_at timestamptz not null default now(),
 unique(user_id,snapshot_day)
);
alter table public.nivora_portfolio_snapshots enable row level security;
drop policy if exists "portfolio_snapshots_select_own" on public.nivora_portfolio_snapshots;
create policy "portfolio_snapshots_select_own" on public.nivora_portfolio_snapshots for select using (auth.uid()=user_id);
drop policy if exists "portfolio_snapshots_insert_own" on public.nivora_portfolio_snapshots;
create policy "portfolio_snapshots_insert_own" on public.nivora_portfolio_snapshots for insert with check (auth.uid()=user_id);
drop policy if exists "portfolio_snapshots_update_own" on public.nivora_portfolio_snapshots;
create policy "portfolio_snapshots_update_own" on public.nivora_portfolio_snapshots for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create index if not exists nivora_portfolio_snapshots_user_day_idx on public.nivora_portfolio_snapshots(user_id,snapshot_day desc);
