create table if not exists public.nivora_v61_trade_evaluations (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 evaluated_at timestamptz not null default now(),
 evaluation_key text not null unique,
 snapshot_id text not null,
 symbol text not null,
 today_action text,
 status text not null,
 reason text not null,
 risk_code text,
 client_order_id text,
 engine_version text not null,
 trading_lab_version text not null,
 details jsonb not null default '{}'::jsonb
);
create index if not exists nivora_v61_trade_evaluations_symbol_time_idx on public.nivora_v61_trade_evaluations(symbol,evaluated_at desc);
create index if not exists nivora_v61_trade_evaluations_status_time_idx on public.nivora_v61_trade_evaluations(status,evaluated_at desc);
alter table public.nivora_v61_trade_evaluations enable row level security;
-- Server/service-role managed. No public client policies are created.
