create table if not exists public.nivora_v61_trade_intents (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 intent_id text not null unique,
 symbol text not null,
 snapshot_id text,
 evidence_fingerprint text,
 side text not null check (side in ('BUY','SELL')),
 intent_type text not null check (intent_type in ('ENTER','ADD','TRIM','EXIT')),
 target_notional numeric,
 approved_notional numeric,
 status text not null,
 risk_code text,
 risk_reason text,
 engine_version text not null,
 trading_lab_version text not null,
 source_intent jsonb not null default '{}'::jsonb,
 source_context jsonb not null default '{}'::jsonb
);
create index if not exists nivora_v61_trade_intents_symbol_created_idx on public.nivora_v61_trade_intents(symbol,created_at desc);

create table if not exists public.nivora_v61_paper_orders (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 intent_id text not null references public.nivora_v61_trade_intents(intent_id) on delete restrict,
 broker text not null default 'alpaca',
 broker_order_id text,
 client_order_id text not null unique,
 symbol text not null,
 side text not null,
 qty numeric not null,
 limit_price numeric,
 status text not null,
 submitted_at timestamptz,
 order_payload jsonb not null default '{}'::jsonb,
 broker_response jsonb not null default '{}'::jsonb
);
create index if not exists nivora_v61_paper_orders_symbol_created_idx on public.nivora_v61_paper_orders(symbol,created_at desc);

create table if not exists public.nivora_v61_trade_fills (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 order_id bigint references public.nivora_v61_paper_orders(id) on delete restrict,
 broker_fill_id text unique,
 symbol text not null,
 side text not null,
 qty numeric not null,
 fill_price numeric not null,
 filled_at timestamptz not null,
 fees numeric not null default 0,
 realized_pnl numeric,
 return_pct numeric,
 benchmark_return_pct numeric,
 evidence jsonb not null default '{}'::jsonb
);
create index if not exists nivora_v61_trade_fills_symbol_filled_idx on public.nivora_v61_trade_fills(symbol,filled_at desc);

alter table public.nivora_v61_trade_intents enable row level security;
alter table public.nivora_v61_paper_orders enable row level security;
alter table public.nivora_v61_trade_fills enable row level security;
-- Trading Lab tables are server/service-role managed. No public client policies are created.
