"use client";
import PriceChart from "@/components/PriceChart";
import {formatMoney} from "@/lib/nivora-format";
import type {InstitutionalDecision} from "@/lib/auryn/v931/domain";

const num=(x:any)=>x==null||x===""?null:Number.isFinite(Number(x))?Number(x):null;
const money=(x:any)=>num(x)==null?"—":formatMoney(Number(x));
const pretty=(x:any)=>String(x||"—").replaceAll("_"," ");
const band=(x:number|null)=>x==null?"BUILDING":x>=75?"STRONG":x>=60?"CONSTRUCTIVE":x>=45?"MIXED":"WEAK";
const companyBand=(x:number|null)=>x==null?"BUILDING":x>=85?"ELITE COMPOUNDER":x>=72?"HIGH QUALITY":x>=58?"SOLID":x>=43?"MIXED":"CHALLENGED";
const valueBand=(x:number|null)=>x==null?"BUILDING":x>=75?"ATTRACTIVE":x>=60?"REASONABLE":x>=45?"FAIR / RICH":"EXPENSIVE";
const pos=(value:number|null,all:Array<number|null>)=>{if(value==null)return 50;const a=all.filter((v):v is number=>v!=null&&Number.isFinite(v));if(a.length<2)return 50;const lo=Math.min(...a),hi=Math.max(...a);return hi===lo?50:5+(value-lo)/(hi-lo)*90};

export default function AurynResearchOverviewV2({decision,marketTruth,displayPrice,displayPriceLive=false,marketIntelligence=null,fundamentalScenario=null,analystFundamentals=null,technicalEvidence=null,entryQuality=null,chartRange="3M",chartLoading=false,onChartRangeChange,onOpenCatalysts,onOpenRisks,onOpenDetails,onOpenThesis,onOpenValuation,candles=[],chartLevels=null}:{decision:InstitutionalDecision;marketTruth:any;displayPrice?:number|null;displayPriceLive?:boolean;marketIntelligence?:any;fundamentalScenario?:any;analystFundamentals?:any;technicalEvidence?:any;entryQuality?:number|null;chartRange?:"1D"|"1W"|"1M"|"3M"|"6M"|"1Y"|"3Y"|"5Y";chartLoading?:boolean;onChartRangeChange?:(x:any)=>void;onOpenCatalysts?:()=>void;onOpenRisks?:()=>void;onOpenDetails?:()=>void;onOpenThesis?:()=>void;onOpenValuation?:()=>void;candles:any[];chartLevels:any}){
 const current=num(displayPrice??marketTruth?.price), business=num(decision.pillars.business.score), valuation=analystFundamentals?num(analystFundamentals.valuationScore):num(decision.pillars.valuation.score), timing=num(entryQuality??decision.pillars.marketStructure.score);
 const dims=analystFundamentals?.companyDimensions||{}, relative=analystFundamentals?.relativeContext||{}, valuationState=analystFundamentals?.valuationState||"UNAVAILABLE", valuationMethod=analystFundamentals?.method||"BUILDING", margin=num(analystFundamentals?.marginOfSafety), fair=num(analystFundamentals?.fairValue);
 const levels=chartLevels||{}, thesis=num(levels.invalidation), support=num(levels.majorSupport??levels.support), eLow=num(levels.entryLow??levels.preferredEntry), eHigh=num(levels.entryHigh??levels.preferredEntry), confirm=num(levels.confirm??levels.breakout), t1=num(levels.t1??levels.target1), t2=num(levels.t2??levels.target2);
 const rail=[thesis,support,eLow,eHigh,current,confirm,t1,t2];
 const decisionLane=(value:number|null)=>{if(value==null)return 0;const p=pos(value,rail);const close=rail.filter(v=>v!=null&&v!==value&&Math.abs(pos(v,rail)-p)<7).length;return close?1:0;};
 const scorePct=(x:number|null)=>x==null?0:Math.max(0,Math.min(100,x));
 const scoreRing=(x:number|null,label:string)=><div className="v99915IndicatorIcon" style={{"--score":`${scorePct(x)}%`} as any} aria-label={`${label} indicator`}><i/></div>;
 const stateBadge=(title:string,sub:string,tone="good")=><div className={`v2StateBadge v99914ContextBadge ${tone}`}><b>{title}</b><small>{sub}</small></div>;
 const businessMetricRows=[["Growth",dims.growth],["Profitability",dims.profitability],["Cash Flow",dims.cashGeneration],["Moat",dims.durability],["Balance Sheet",dims.balanceSheet],["Execution",dims.forwardEvidence]];
 const valuationRows=[["vs History",relative.vsHistory],["vs Peers",relative.vsPeers],["Growth Adj",relative.growthAdjusted],["FCF Yield",num(relative.fcfYield)==null?null:`${Number(relative.fcfYield).toFixed(1)}%`],["Margin of Safety",margin==null?null:`${margin>=0?"+":""}${margin.toFixed(1)}%`]];
 const combinedThesisSupport=thesis!=null&&support!=null&&Math.abs(thesis-support)<0.005;
 const mapNodes=combinedThesisSupport?[["THESIS / SUPPORT",thesis,"risk"],["Entry Range",eLow,"entry"],["Current",current,"current"],["Confirm",confirm,"confirm"],["T1",t1,"target"],["T2",t2,"target"]]:[["Thesis",thesis,"risk"],["Support",support,"support"],["Entry Range",eLow,"entry"],["Current",current,"current"],["Confirm",confirm,"confirm"],["T1",t1,"target"],["T2",t2,"target"]];


 const catalysts=[decision.pillars.catalystsRegime.why,...(decision.drivers||[])].filter(Boolean).slice(0,3);
 const risks=[...(decision.counterEvidence||[]),...(decision.hardVetoReasons||[])].filter(Boolean).slice(0,3);
 const timingMetrics=[
  ["Trend",num(technicalEvidence?.trend)?.toFixed(0)||"—"],
  ["Momentum",num(technicalEvidence?.momentum)?.toFixed(0)||"—"],
  ["Participation",num(technicalEvidence?.participation)?.toFixed(0)||"—"],
  ["Relative strength",num(technicalEvidence?.relativeStrengthPct)!=null?`${Number(technicalEvidence.relativeStrengthPct)>=0?"+":""}${Number(technicalEvidence.relativeStrengthPct).toFixed(1)}%`:"—"],
  ["Volatility",num(technicalEvidence?.volatilityRisk)!=null?`${Math.round(Number(technicalEvidence.volatilityRisk))}/100`:"—"]
 ];
 return <section className="aurynOverviewV2">
  <div className="v2DecisionHero v99914Hero">
   <article className="v2Call"><small>AURYN CALL</small><h1>{pretty(decision.newMoneyAction)}</h1><p>{decision.pillars.business.why}</p><div className="v2Actions v99914CallActions"><span>New Money <b>{pretty(decision.newMoneyAction)}</b></span><span>Owner <b>{pretty(decision.ownerAction)}</b></span><span>Long Term <b>{pretty(decision.longTermAction)}</b></span></div><footer><span>Confidence {decision.confidenceScore}/100</span><span>Evidence {decision.evidenceCompleteness}/100</span><span>Last Updated<br/>{marketTruth?.decisionPriceAsOf?new Date(marketTruth.decisionPriceAsOf).toLocaleDateString():"—"}</span></footer></article>
   <article className="v2Chart"><header><small>PRICE CHART</small><b>{displayPriceLive?"LIVE":"VERIFIED RESEARCH"}</b></header><div className="v99914Ranges">{["1D","1W","1M","3M","6M","1Y","3Y","5Y"].map(x=><button type="button" onClick={()=>onChartRangeChange?.(x)} className={x===chartRange?"active":""} key={x}>{x}</button>)}</div><div className={`v99915ChartStage ${chartLoading?"loading":""}`}><PriceChart candles={candles} levels={chartLevels}/>{chartLoading?<span className="v99915ChartLoading">Loading {chartRange}…</span>:null}</div></article>
   <article className="v2Structure"><header><small>PRICE STRUCTURE</small><b>{band(timing)}</b></header>{[["Target 2",t2],["Target 1",t1],["Confirm",confirm],["Current",current],["Entry Range",eLow!=null&&eHigh!=null?`${money(eLow)} – ${money(eHigh)}`:"—"],["Major Support",support],["Thesis Break",thesis]].map(([k,v]:any)=><div key={k}><span>{k}</span><b>{typeof v==="string"?v:money(v)}</b></div>)}</article>
  </div>

  <div className="v2AnalystClocks">
   <article className="v2AnalystCard"><header><div><small>1. BUSINESS QUALITY</small><h3>{companyBand(business)}</h3></div>{scoreRing(business,"QUALITY")}</header><div className="v2CardLead"><p>{business==null?"Evidence building":`${business.toFixed(0)}/100`}</p>{stateBadge(pretty(analystFundamentals?.trajectory||"BUILDING"),"Trajectory")}</div><p className="v2CardSummary">{decision.pillars.business.why}</p><div className="v2MetricStrip">{businessMetricRows.map(([k,v])=><span key={k as string}><small>{k}</small><b>{num(v)==null?"—":Math.round(Number(v))}</b></span>)}</div></article>
   <article className="v2AnalystCard"><header><div><small>2. VALUATION</small><h3>{valuation==null?valuationState:valueBand(valuation)}</h3></div>{valuationState==="PARTIAL"?<div className="v99915IndicatorIcon partial" aria-label="Partial valuation"><i/></div>:scoreRing(valuation,"VALUE")}</header><div className="v2CardLead"><p>{valuation==null?pretty(valuationMethod):`${valuation.toFixed(0)}/100`}</p>{stateBadge(margin==null?valuationState:(margin>=10?"Attractive":margin>=-10?"Neutral":"Expensive"),margin==null?"Evidence":"vs Fair Value",margin!=null&&margin<-10?"warn":"good")}</div><p className="v2CardSummary">{margin==null?"AURYN withholds precise fair value until the routed valuation method has sufficient evidence.":`Model margin of safety is ${margin>=0?"+":""}${margin.toFixed(1)}%.`}</p><div className="v2MetricStrip v2ValueStrip">{valuationRows.map(([k,v])=><span key={k as string}><small>{k}</small><b>{v??"—"}</b></span>)}</div></article>
   <article className="v2AnalystCard"><header><div><small>3. MARKET TIMING</small><h3>{band(timing)}</h3></div>{scoreRing(timing,"TIMING")}</header><div className="v2CardLead"><p>{timing==null?"Building":`${timing.toFixed(0)}/100`}</p>{stateBadge(num(technicalEvidence?.trend)!=null&&Number(technicalEvidence.trend)>=60?"Improving":num(technicalEvidence?.trend)!=null&&Number(technicalEvidence.trend)<45?"Weakening":"Neutral","Trend",num(technicalEvidence?.trend)!=null&&Number(technicalEvidence.trend)<45?"warn":"good")}</div><p className="v2CardSummary">Price structure, participation and relative performance determine entry timing independently of long-term business quality.</p><div className="v2MetricStrip">{timingMetrics.map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div></article>
  </div>

  <div className="v2DecisionVisuals">
   <article className="v2Scenario"><header><small>SCENARIO SPECTRUM</small><h2>Fundamental value</h2><span>Decision-grade assumptions · not probabilities</span></header>{valuationState==="PARTIAL"?<div className="v99914PartialScenario"><b>Valuation Model: Partial</b><p>AURYN is building the full scenario analysis. Available evidence remains visible; historical, peer and method-specific cross-checks are required before publishing Bear / Base / Bull fair values.</p><button type="button" onClick={onOpenValuation} className="v2TextAction">View Valuation Evidence →</button></div>:fundamentalScenario?<><div className="v2SpectrumWrap"><div className="v2ScenarioCurrentMarker">CURRENT <b>{money(current)}</b></div><div className="v2SpectrumTrack"><i className="bear"/><i className="base"/><i className="bull"/></div><div className="v2ScenarioRail">{["bear","base","bull"].map(k=>{const v=num(fundamentalScenario[k]?.value),d=current&&v!=null?(v/current-1)*100:null;return <span key={k}><small>{k.toUpperCase()}</small><b>{money(v)}</b><em>{d==null?"—":`${d>=0?"+":""}${d.toFixed(1)}%`}</em></span>})}</div></div><div className="v2ScenarioCases"><span><b>Bear Case</b><small>Growth slows, cash-flow durability weakens and the required return rises.</small></span><span><b>Base Case</b><small>Current source-backed economics normalize through the explicit valuation policy.</small></span><span><b>Bull Case</b><small>Growth persists longer and cash-flow conversion exceeds the normalized base path.</small></span></div><div className="v2ScenarioAssumptions"><span>Revenue growth <b>{fundamentalScenario.assumptions?.observedRevenueGrowthPct==null?"—":`${Number(fundamentalScenario.assumptions.observedRevenueGrowthPct).toFixed(1)}%`}</b></span><span>FCF <b>{money(fundamentalScenario.assumptions?.currentFcf)}</b></span><span>Discount <b>{fundamentalScenario.assumptions?.baseDiscountRate}%</b></span><span>Terminal <b>{fundamentalScenario.assumptions?.baseTerminalGrowth}%</b></span></div><button type="button" onClick={onOpenValuation} className="v2TextAction">View Full Scenario Analysis →</button></>:<div className="v2Building"><b>Fundamental valuation building</b><span>AURYN publishes fair value only when the routed valuation method has sufficient source-backed inputs.</span></div>}</article>
   <article className="v2DecisionMap"><header><small>DECISION MAP</small><h2>Execution plan</h2><span>Where we are in the canonical investment plan</span></header><div className="v2DecisionMapBody">{current!=null?<div className="v2CurrentMapMarker" style={{left:`${pos(current,rail)}%`}}>CURRENT <b>{money(current)}</b></div>:null}<div className="v2Rail">{mapNodes.filter(([,v])=>v!=null).map(([k,v,c]:any)=><span className={`${c} lane-${decisionLane(v)}`} key={k} style={{left:`${pos(v,rail)}%`}}><i/><span className="v2RailConnector"/><small>{k}</small><b>{money(v)}</b></span>)}</div><div className="v2DecisionZones"><span>THESIS RISK ←</span><span>ENTRY / ACCUMULATION</span><span>CONFIRM / TARGETS →</span></div></div><p>{current!=null&&confirm!=null&&current<confirm?`Price is below confirmation at ${money(confirm)}. Wait for confirmation or a pullback into the mapped entry range for better risk/reward.`:`Current price is evaluated against the canonical execution map while business quality and fair value remain separate decisions.`}</p></article>
  </div>

  <div className="v2Synthesis v99914BottomGrid v99916Insights">
   <article><small>KEY CATALYSTS</small>{catalysts.length?catalysts.map((x,i)=><div className="v2AnalystRow good" key={i}><i>↗</i><span><b>{i===0?"Forward evidence":i===1?"Business driver":"Catalyst"}</b><small>{x}</small></span></div>):<div className="v2AnalystRow"><span><b>No decision-grade catalyst loaded</b></span></div>}<button type="button" onClick={onOpenCatalysts} className="v2TextAction">View All Catalysts →</button></article>
   <article><small>KEY RISKS</small>{risks.length?risks.map((x,i)=><div className="v2AnalystRow bad" key={i}><i>!</i><span><b>{i===0?"Primary risk":"Risk evidence"}</b><small>{x}</small></span></div>):<div className="v2AnalystRow"><span><b>No material canonical risk loaded</b></span></div>}<button type="button" onClick={onOpenRisks} className="v2TextAction">View All Risks →</button></article>
   <article><small>WHAT'S CHANGED</small><h3>{decision.changeExplanation?.changed?"Evidence changed":"No canonical state change"}</h3><div className="v2AnalystRow"><i>→</i><span><b>Revenue estimates</b><small>Comparable snapshot required</small></span></div><div className="v2AnalystRow"><i>→</i><span><b>EPS estimates</b><small>Comparable snapshot required</small></span></div><div className="v2AnalystRow"><i>→</i><span><b>Margin outlook</b><small>{pretty(analystFundamentals?.trajectory||"Building")}</small></span></div><div className="v2AnalystRow"><i>→</i><span><b>Technical structure</b><small>{band(timing)}</small></span></div><div className="v2AnalystRow"><i>→</i><span><b>Valuation</b><small>{valuation==null?valuationState:valueBand(valuation)}</small></span></div><button type="button" onClick={onOpenDetails} className="v2TextAction">View Details →</button></article>
   <article><small>AURYN VIEW</small><h3>{pretty(decision.newMoneyAction)}</h3><p>{companyBand(business)} business with {pretty(analystFundamentals?.trajectory||"building").toLowerCase()} trajectory. Valuation is {valuation==null?valuationState.toLowerCase():valueBand(valuation).toLowerCase()} and market timing is {band(timing).toLowerCase()}. Owner: {pretty(decision.ownerAction)} · Long term: {pretty(decision.longTermAction)}.</p><button type="button" onClick={onOpenThesis} className="v2TextAction">View Full Thesis →</button></article>
  </div>
 </section>;
}
