import type {BusinessModel,CanonicalFactorKey,LifecycleStage,PrimaryInvestmentAction,SecurityClassification} from "./domain";

export interface AnalystModelDefinition {
  id:string;
  version:string;
  businessModels:BusinessModel[];
  lifecycle?:LifecycleStage[];
  factorWeights:Partial<Record<CanonicalFactorKey,number>>;
  requiredFactors:CanonicalFactorKey[];
  optionalFactors:CanonicalFactorKey[];
  allowOptionalRenormalization:boolean;
  maxActionWhenSuitabilityLow:PrimaryInvestmentAction;
}

const common={version:"auryn-v4-model-1",allowOptionalRenormalization:true,maxActionWhenSuitabilityLow:"HOLD" as const};

export const ANALYST_MODELS:AnalystModelDefinition[]=[
  {...common,id:"general-compounder",businessModels:["GENERAL_COMPOUNDER","CONSUMER","INDUSTRIAL"],factorWeights:{BUSINESS_QUALITY:.16,GROWTH_INFLECTION:.12,MOAT:.13,NARRATIVE_EXPECTATIONS:.06,FUNDAMENTALS_EARNINGS:.13,VALUATION:.12,TECHNICALS:.06,POSITIONING:.03,CATALYSTS:.05,SECTOR_INDUSTRY:.06,MACRO_REGIME:.02,RISK:.06},requiredFactors:["BUSINESS_QUALITY","FUNDAMENTALS_EARNINGS","VALUATION","RISK"],optionalFactors:["GROWTH_INFLECTION","MOAT","NARRATIVE_EXPECTATIONS","TECHNICALS","POSITIONING","CATALYSTS","SECTOR_INDUSTRY","MACRO_REGIME"]},
  {...common,id:"software-marketplace",businessModels:["SAAS_SOFTWARE","MARKETPLACE_ADTECH","FINTECH_PAYMENTS"],factorWeights:{BUSINESS_QUALITY:.15,GROWTH_INFLECTION:.16,MOAT:.15,NARRATIVE_EXPECTATIONS:.08,FUNDAMENTALS_EARNINGS:.11,VALUATION:.12,TECHNICALS:.05,POSITIONING:.02,CATALYSTS:.05,SECTOR_INDUSTRY:.04,MACRO_REGIME:.01,RISK:.06},requiredFactors:["BUSINESS_QUALITY","GROWTH_INFLECTION","VALUATION","RISK"],optionalFactors:["MOAT","NARRATIVE_EXPECTATIONS","FUNDAMENTALS_EARNINGS","TECHNICALS","POSITIONING","CATALYSTS","SECTOR_INDUSTRY","MACRO_REGIME"]},
  {...common,id:"semiconductor-designer-networking",businessModels:["SEMICONDUCTOR_DESIGNER","NETWORKING_COMPUTE_INFRA"],factorWeights:{BUSINESS_QUALITY:.12,GROWTH_INFLECTION:.15,MOAT:.16,NARRATIVE_EXPECTATIONS:.07,FUNDAMENTALS_EARNINGS:.11,VALUATION:.10,TECHNICALS:.06,POSITIONING:.03,CATALYSTS:.06,SECTOR_INDUSTRY:.07,MACRO_REGIME:.02,RISK:.05},requiredFactors:["GROWTH_INFLECTION","MOAT","FUNDAMENTALS_EARNINGS","VALUATION","RISK"],optionalFactors:["BUSINESS_QUALITY","NARRATIVE_EXPECTATIONS","TECHNICALS","POSITIONING","CATALYSTS","SECTOR_INDUSTRY","MACRO_REGIME"]},
  {...common,id:"semiconductor-memory-cycle",businessModels:["SEMICONDUCTOR_MEMORY_CYCLICAL"],factorWeights:{BUSINESS_QUALITY:.07,GROWTH_INFLECTION:.17,MOAT:.06,NARRATIVE_EXPECTATIONS:.05,FUNDAMENTALS_EARNINGS:.12,VALUATION:.10,TECHNICALS:.08,POSITIONING:.03,CATALYSTS:.05,SECTOR_INDUSTRY:.15,MACRO_REGIME:.06,RISK:.06},requiredFactors:["GROWTH_INFLECTION","FUNDAMENTALS_EARNINGS","SECTOR_INDUSTRY","VALUATION","RISK"],optionalFactors:["BUSINESS_QUALITY","MOAT","NARRATIVE_EXPECTATIONS","TECHNICALS","POSITIONING","CATALYSTS","MACRO_REGIME"]},
  {...common,id:"ai-power-infrastructure",businessModels:["AI_DATA_CENTER_INFRA","POWER_UTILITY_INFRA"],factorWeights:{BUSINESS_QUALITY:.10,GROWTH_INFLECTION:.15,MOAT:.10,NARRATIVE_EXPECTATIONS:.07,FUNDAMENTALS_EARNINGS:.10,VALUATION:.10,TECHNICALS:.06,POSITIONING:.03,CATALYSTS:.10,SECTOR_INDUSTRY:.07,MACRO_REGIME:.03,RISK:.09},requiredFactors:["GROWTH_INFLECTION","FUNDAMENTALS_EARNINGS","CATALYSTS","RISK"],optionalFactors:["BUSINESS_QUALITY","MOAT","NARRATIVE_EXPECTATIONS","VALUATION","TECHNICALS","POSITIONING","SECTOR_INDUSTRY","MACRO_REGIME"]},
  {...common,id:"frontier-pre-scale",businessModels:["SPACE_SATELLITE"],lifecycle:["PRE_COMMERCIAL","VALIDATION","INFLECTION","HYPERGROWTH"],factorWeights:{BUSINESS_QUALITY:.05,GROWTH_INFLECTION:.15,MOAT:.18,NARRATIVE_EXPECTATIONS:.08,FUNDAMENTALS_EARNINGS:.05,VALUATION:.08,TECHNICALS:.04,POSITIONING:.02,CATALYSTS:.13,SECTOR_INDUSTRY:.05,MACRO_REGIME:.02,RISK:.15},requiredFactors:["MOAT","GROWTH_INFLECTION","CATALYSTS","RISK"],optionalFactors:["BUSINESS_QUALITY","NARRATIVE_EXPECTATIONS","FUNDAMENTALS_EARNINGS","VALUATION","TECHNICALS","POSITIONING","SECTOR_INDUSTRY","MACRO_REGIME"]},
  {...common,id:"financials",businessModels:["BANK","INSURER","FINTECH_PAYMENTS"],factorWeights:{BUSINESS_QUALITY:.16,GROWTH_INFLECTION:.07,MOAT:.08,NARRATIVE_EXPECTATIONS:.04,FUNDAMENTALS_EARNINGS:.17,VALUATION:.15,TECHNICALS:.04,POSITIONING:.02,CATALYSTS:.03,SECTOR_INDUSTRY:.08,MACRO_REGIME:.08,RISK:.08},requiredFactors:["BUSINESS_QUALITY","FUNDAMENTALS_EARNINGS","VALUATION","MACRO_REGIME","RISK"],optionalFactors:["GROWTH_INFLECTION","MOAT","NARRATIVE_EXPECTATIONS","TECHNICALS","POSITIONING","CATALYSTS","SECTOR_INDUSTRY"]},
  {...common,id:"biotech-pre-profit",businessModels:["BIOTECH_PHARMA","MEDTECH"],factorWeights:{BUSINESS_QUALITY:.05,GROWTH_INFLECTION:.08,MOAT:.12,NARRATIVE_EXPECTATIONS:.05,FUNDAMENTALS_EARNINGS:.05,VALUATION:.06,TECHNICALS:.03,POSITIONING:.02,CATALYSTS:.22,SECTOR_INDUSTRY:.05,MACRO_REGIME:.02,RISK:.25},requiredFactors:["CATALYSTS","RISK","MOAT"],optionalFactors:["BUSINESS_QUALITY","GROWTH_INFLECTION","NARRATIVE_EXPECTATIONS","FUNDAMENTALS_EARNINGS","VALUATION","TECHNICALS","POSITIONING","SECTOR_INDUSTRY","MACRO_REGIME"]},
  {...common,id:"reit",businessModels:["REIT"],factorWeights:{BUSINESS_QUALITY:.15,GROWTH_INFLECTION:.06,MOAT:.05,NARRATIVE_EXPECTATIONS:.03,FUNDAMENTALS_EARNINGS:.14,VALUATION:.18,TECHNICALS:.04,POSITIONING:.02,CATALYSTS:.03,SECTOR_INDUSTRY:.09,MACRO_REGIME:.12,RISK:.09},requiredFactors:["BUSINESS_QUALITY","FUNDAMENTALS_EARNINGS","VALUATION","MACRO_REGIME","RISK"],optionalFactors:["GROWTH_INFLECTION","MOAT","NARRATIVE_EXPECTATIONS","TECHNICALS","POSITIONING","CATALYSTS","SECTOR_INDUSTRY"]},
  {...common,id:"energy-miner-cycle",businessModels:["ENERGY","MINER_COMMODITY"],factorWeights:{BUSINESS_QUALITY:.08,GROWTH_INFLECTION:.08,MOAT:.04,NARRATIVE_EXPECTATIONS:.03,FUNDAMENTALS_EARNINGS:.11,VALUATION:.10,TECHNICALS:.06,POSITIONING:.03,CATALYSTS:.05,SECTOR_INDUSTRY:.16,MACRO_REGIME:.12,RISK:.14},requiredFactors:["FUNDAMENTALS_EARNINGS","VALUATION","SECTOR_INDUSTRY","MACRO_REGIME","RISK"],optionalFactors:["BUSINESS_QUALITY","GROWTH_INFLECTION","MOAT","NARRATIVE_EXPECTATIONS","TECHNICALS","POSITIONING","CATALYSTS"]}
];

export function selectAnalystModel(c:SecurityClassification):{definition:AnalystModelDefinition;suitability:number}{
  const candidates=ANALYST_MODELS.filter(d=>d.businessModels.includes(c.businessModel));
  const lifecycleSpecific=candidates.find(d=>d.lifecycle?.includes(c.lifecycle));
  const definition=lifecycleSpecific??candidates.find(d=>!d.lifecycle)??candidates[0]??ANALYST_MODELS[0];
  const businessMatch=definition.businessModels.includes(c.businessModel)?1:0;
  const lifecycleMatch=!definition.lifecycle?0.8:definition.lifecycle.includes(c.lifecycle)?1:0.35;
  let suitability=Math.max(0,Math.min(1,c.confidence*.65+businessMatch*.20+lifecycleMatch*.15));
  if(!candidates.length)suitability=Math.min(.55,suitability);
  return{definition,suitability:+suitability.toFixed(3)};
}
