import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {AURYN_V6_ENGINE_VERSION} from '@/lib/auryn/v6/version';
import {measureOutcome} from '@/lib/v65/outcomes';
export const dynamic='force-dynamic';
const horizons=[['30D',30],['90D',90],['180D',180],['1Y',365],['2Y',730]] as const,day=86400000;
type DailyBar={date:string;close:number};
const auth=(req:Request)=>{const secret=process.env.TRADING_LAB_CRON_SECRET||process.env.CRON_SECRET;return Boolean(secret&&req.headers.get('authorization')===`Bearer ${secret}`)};
const iso=(d:Date)=>d.toISOString().slice(0,10);
async function series(symbol:string,start:string,end:string,key:string):Promise<DailyBar[]>{const u=new URL('https://api.twelvedata.com/time_series');u.searchParams.set('symbol',symbol);u.searchParams.set('interval','1day');u.searchParams.set('start_date',start);u.searchParams.set('end_date',end);u.searchParams.set('adjust','all');u.searchParams.set('outputsize','800');u.searchParams.set('apikey',key);const r=await fetch(u,{cache:'no-store',signal:AbortSignal.timeout(10000)}),j=await r.json();if(!r.ok||!Array.isArray(j?.values))throw new Error(j?.message||`No daily series for ${symbol}`);return j.values.slice().reverse().map((x:any)=>({date:String(x.datetime).slice(0,10),close:Number(x.close)})).filter((x:any)=>Number.isFinite(x.close)&&x.close>0)}
const atOrAfter=(rows:DailyBar[],date:string)=>rows.find(x=>x.date>=date)||null;
export async function GET(req:Request){
 if(!auth(req))return NextResponse.json({error:'Unauthorized.'},{status:401});
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,td=process.env.TWELVE_DATA_API_KEY;if(!url||!key||!td)return NextResponse.json({status:'unavailable',reason:'Supabase service credentials and Twelve Data are required.'},{status:503});
 const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),now=new Date(),oldest30=new Date(now.getTime()-30*day).toISOString();
 const{data:candidates,error}=await db.from('nivora_v59_decision_snapshots').select('id,symbol,observed_at,price,benchmark_symbol').eq("engine_version",AURYN_V6_ENGINE_VERSION).lte('observed_at',oldest30).order('observed_at',{ascending:true}).limit(12);if(error)return NextResponse.json({status:'error',error:error.message},{status:500});
 const ids=(candidates||[]).map((x:any)=>Number(x.id));const{data:existing}=ids.length?await db.from('nivora_v59_arena_outcomes').select('snapshot_id,horizon').in('snapshot_id',ids):{data:[] as any[]};const exists=new Set((existing||[]).map((x:any)=>`${x.snapshot_id}|${x.horizon}`));let inserted=0,skipped=0,failed=0;const errors:string[]=[];
 for(const snap of candidates||[]){try{const observed=new Date(snap.observed_at),start=iso(new Date(observed.getTime()-3*day)),end=iso(now),[stock,bench]=await Promise.all([series(String(snap.symbol),start,end,td),series(String(snap.benchmark_symbol||'SPY'),start,end,td)]),benchStart=atOrAfter(bench,iso(observed));if(!benchStart)throw new Error(`No benchmark start bar for ${snap.symbol}`);for(const[h,days]of horizons){if(now.getTime()-observed.getTime()<days*day||exists.has(`${snap.id}|${h}`))continue;const target=iso(new Date(observed.getTime()+days*day)),endStock=atOrAfter(stock,target),endBench=atOrAfter(bench,target);if(!endStock||!endBench){skipped++;continue}const path=stock.filter(x=>x.date<=endStock.date).map(x=>x.close),m=measureOutcome({entryPrice:Number(snap.price),endPrice:endStock.close,benchmarkStart:benchStart.close,benchmarkEnd:endBench.close,pathPrices:path});const{error:ie}=await db.from('nivora_v59_arena_outcomes').upsert({snapshot_id:snap.id,horizon:h,outcome_at:`${endStock.date}T21:00:00Z`,end_price:endStock.close,raw_return_pct:m.rawReturnPct,benchmark_return_pct:m.benchmarkReturnPct,alpha_pct:m.alphaPct,max_drawdown_pct:m.maxDrawdownPct,hit:m.hit},{onConflict:'snapshot_id,horizon'});if(ie)throw ie;inserted++}}catch(e:any){failed++;errors.push(`${snap.symbol}: ${e?.message||e}`)}}
 return NextResponse.json({status:'ok',engineVersion:AURYN_V6_ENGINE_VERSION,candidates:(candidates||[]).length,inserted,skipped,failed,errors:errors.slice(0,10),note:'V6 outcomes mature into proof evidence only; production coefficients remain frozen.'},{headers:{'Cache-Control':'private, no-store'}});
}
