import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const mod=await import('../.engine-test/auryn/v934/projections.js').catch(()=>({}));
const {projectMarketIntelligence}=mod;
const sample={version:'auryn-market-intelligence-v934',snapshotId:'IREN-mi-1',fingerprint:'abc',symbol:'IREN',asOf:'2026-09-10T18:00:00.000Z',marketTruthSnapshotId:'IREN-market-1',session:'REGULAR',calendarState:'OPEN',displayPrice:45.2,decisionPrice:45.2,priceState:'LIVE_VERIFIED',priceUse:'LIVE_EXECUTION',confirmed:{'4H':{rating:'BUY',score:44},'1D':{rating:'NEUTRAL',score:8},'1W':{rating:'BUY',score:36}},livePreview:{'1D':{rating:'SELL',score:-24}},actionMap:{preferredEntry:{low:42.8,high:44.2,confidence:'HIGH',evidence:[]},confirm:47.65,support:42.8,majorSupport:40.1,invalidation:38.9,t1:51.2,t2:57.4,asOf:'2026-09-09',zones:[],supportZone:null,resistanceZone:null},summary:{primaryTimeframe:'1D',confirmedRating:'NEUTRAL',liveRating:'SELL',alignment:'BULLISH_BIAS',researchActive:true},coverage:{requested:['15M','1H','4H','1D','1W'],confirmed:['4H','1D','1W'],preview:['1D'],missing:['15M','1H']}};

test('market intelligence projection keeps one snapshot identity and actionable levels',()=>{const p=projectMarketIntelligence(sample);assert.equal(p.snapshotId,'IREN-mi-1');assert.equal(p.marketTruthSnapshotId,'IREN-market-1');assert.equal(p.timeframes['1D'].confirmed,'NEUTRAL');assert.equal(p.timeframes['1D'].livePreview,'SELL');assert.equal(p.levels.confirm,47.65);assert.equal(p.levels.invalidation,38.9);});

test('validation snapshot persists the V9.3.4 projection beside the canonical decision',()=>{const src=fs.readFileSync('components/StockClient.tsx','utf8');assert.match(src,/v934:/);assert.match(src,/projectMarketIntelligence/);});

test('decision summaries publish persisted V9.3.4 intelligence instead of inventing a second technical view',()=>{const src=fs.readFileSync('app/api/decision/summaries/route.ts','utf8');assert.match(src,/evidence\?\.v934/);assert.match(src,/marketIntelligence/);assert.match(src,/actionMap|levels/);});

test('trading lab requires canonical V9.3.4 intelligence and uses its invalidation when available',()=>{const src=fs.readFileSync('app/api/trading-lab/run-paper/route.ts','utf8');assert.match(src,/v934/);assert.match(src,/MARKET_INTELLIGENCE_MISSING/);assert.match(src,/actionMap.*invalidation|levels.*invalidation/s);});
