import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8"),persist=read("lib/auryn/v995/persist-research.ts"),paper=read("app/api/trading-lab/run-paper/route.ts"),status=read("app/api/trading-lab/status/route.ts"),page=read("app/trading-lab/page.tsx");
test("autonomous research persists V935 canonical provenance",()=>{assert.ok(persist.includes("buildV935Provenance"));assert.ok(persist.includes("v935:canonical"));assert.ok(persist.includes("AUTONOMOUS_RESEARCH_ENGINE_VERSION"));});
test("paper runner consumes autonomous canonical research not legacy V65 learning snapshots",()=>{assert.ok(paper.includes("AUTONOMOUS_RESEARCH_ENGINE_VERSION"));assert.ok(!paper.includes('.eq("engine_version",ENGINE_VERSION)'));});
test("status audit consumes same autonomous canonical research",()=>{assert.ok(status.includes("AUTONOMOUS_RESEARCH_ENGINE_VERSION"));assert.ok(status.includes("decisionSnapshotsResult"));});
test("trading lab scheduled auth prefers canonical CRON_SECRET",()=>{for(const p of ["app/api/trading-lab/run-paper/route.ts","app/api/trading-lab/run-now/route.ts"])assert.ok(read(p).includes("process.env.CRON_SECRET||process.env.TRADING_LAB_CRON_SECRET"),p);});
test("UI does not expose obsolete V9.3.5 provenance failure copy",()=>{assert.ok(!page.includes("V9.3.5 canonical snapshot provenance is missing"));assert.ok(page.includes("Canonical research snapshot"));});
test("UI prioritizes current run over lifetime order totals",()=>{assert.ok(page.includes("latestRun"));assert.ok(page.includes("THIS CHECK"));assert.ok(page.includes("Historical paper orders"));});
test("trading lab uses compact decision summary",()=>{for(const x of ["aurynLabCompactFunnel","aurynLabDecisionGrid","aurynLabCurrentRun"])assert.ok(page.includes(x),x);});
