import test from 'node:test';import assert from 'node:assert/strict';
const mod=await import('../.engine-test/auryn/v934/intelligence-snapshot.js').catch(()=>({}));
const {buildAurynMarketIntelligenceSnapshot}=mod;
function bars(n=260,start=100,drift=.2,startDate='2025-01-01'){let p=start;return Array.from({length:n},(_,i)=>{const c=p+drift+Math.sin(i/8)*.18,o=p,h=Math.max(o,c)+1,l=Math.min(o,c)-1;p=c;return{datetime:new Date(Date.UTC(2025,0,1+i)).toISOString().slice(0,10),open:o,high:h,low:l,close:c,volume:1e6+i*1000}})}
const market={snapshotId:'IREN-market-x',symbol:'IREN',asOf:'2026-09-10T18:00:00.000Z',session:'REGULAR',calendarState:'OPEN',priceState:'LIVE_VERIFIED',decisionPrice:45.2,displayPrice:45.2,decisionPriceAsOf:'2026-09-10T17:59:58.000Z',decisionPriceRole:'LIVE_MARKET',regularClose:44.1,regularClosePrice:44.1,regularCloseAsOf:'2026-09-09T20:00:00.000Z',liveMarketPrice:45.2,liveMarketPriceAsOf:'2026-09-10T17:59:58.000Z',executionPrice:45.2,executionPriceAsOf:'2026-09-10T17:59:58.000Z',extendedPrice:null,providerAgreementPct:.05,contextProviderGapPct:.05,sources:[],priceSensitiveAllowed:true,decisionAllowed:true,executionTradable:true,priceUse:'LIVE_EXECUTION',reason:'verified'};

test('snapshot fingerprint is deterministic for identical market and completed bars',()=>{const b={"1D":bars(),"1W":bars(120,60,.55),"4H":bars(180,90,.12)};const a=buildAurynMarketIntelligenceSnapshot({symbol:'IREN',marketTruth:market,confirmedBars:b,benchmarkBars:{},previewBars:{}});const c=buildAurynMarketIntelligenceSnapshot({symbol:'IREN',marketTruth:{...market},confirmedBars:b,benchmarkBars:{},previewBars:{}});assert.equal(a.snapshotId,c.snapshotId);assert.equal(a.fingerprint,c.fingerprint);assert.deepEqual(a.actionMap,c.actionMap);});

test('live preview never rewrites confirmed daily state or structural levels',()=>{const daily=bars(),preview=daily.concat([{...daily.at(-1),datetime:'2026-09-10',close:20,low:18,high:46}]);const a=buildAurynMarketIntelligenceSnapshot({symbol:'IREN',marketTruth:market,confirmedBars:{'1D':daily},benchmarkBars:{},previewBars:{'1D':preview}});assert.ok(a.confirmed['1D']);assert.ok(a.livePreview['1D']);assert.notEqual(a.confirmed['1D'].rating,a.livePreview['1D'].rating);const b=buildAurynMarketIntelligenceSnapshot({symbol:'IREN',marketTruth:market,confirmedBars:{'1D':daily},benchmarkBars:{},previewBars:{}});assert.deepEqual(a.actionMap,b.actionMap);assert.equal(a.confirmed['1D'].rating,b.confirmed['1D'].rating);});

test('closed market remains research active from canonical market truth',()=>{const closed={...market,session:'CLOSED',calendarState:'CLOSED',priceState:'OFFICIAL_CLOSE',decisionPrice:44.1,displayPrice:44.1,executionPrice:null,executionTradable:false,priceUse:'RESEARCH_CLOSE'};const a=buildAurynMarketIntelligenceSnapshot({symbol:'IREN',marketTruth:closed,confirmedBars:{'1D':bars()},benchmarkBars:{},previewBars:{}});assert.equal(a.summary.researchActive,true);assert.equal(a.displayPrice,44.1);assert.equal(a.session,'CLOSED');});
