const m=(x:any)=>Number.isFinite(Number(x))?`$${Number(x).toFixed(2)}`:"—";
export function buildInvestmentNarrative({businessScore,trajectory,valuationState,fairValue,marginOfSafety,roadmap,timingState,activeEntry,setupInvalidation,deepCycleSupport,changed}:any){
 const whyOwn=businessScore==null?"Business evidence is still building.":`${businessScore>=85?"High-quality":"Current"} business evidence scores ${Math.round(businessScore)}/100${trajectory?` with a ${String(trajectory).toLowerCase()} trajectory`:""}.`;
 const whatWorth=fairValue!=null?`Fundamental fair value is ${m(fairValue)}${marginOfSafety!=null?`; model margin of safety is ${Number(marginOfSafety).toFixed(1)}%`:""}.`:`Valuation evidence is ${String(valuationState||"partial").toLowerCase()}; AURYN withholds fair value until the selected method is sufficiently supported.`;
 const whereAccumulate=activeEntry?.low!=null?`Active entry is ${m(activeEntry.low)}–${m(activeEntry.high)}. ${deepCycleSupport!=null?`Deep-cycle support near ${m(deepCycleSupport)} is context only, not today's buy zone.`:""}`:roadmap?.entryLow!=null?`No active daily entry is published; deep-cycle structural support is near ${m(roadmap.entryLow)}–${m(roadmap.entryHigh)}.`:"Entry levels are still building.";
 const whatConfirms=roadmap?.nextTrigger!=null?`The next long-term confirmation is ${m(roadmap.nextTrigger)}${roadmap.wma50?`; the 50-WMA is ${m(roadmap.wma50)}`:""}.`:"Long-term confirmation is still building.";
 const whatBreaks=setupInvalidation!=null?`Today's setup invalidates below ${m(setupInvalidation)}. ${roadmap?.invalidation!=null?`Long-term structural failure is separate at ${m(roadmap.invalidation)}.`:""} Business-thesis deterioration is evaluated separately.`:roadmap?.invalidation!=null?`Long-term structural failure is ${m(roadmap.invalidation)}; no separate daily setup invalidation is published.`:"No decision-grade structural invalidation is published yet.";
 const whatChanged=changed||"No canonical long-term thesis change is confirmed on this snapshot.";
 const nextDecision=`${timingState||"Current timing"} remains the execution state. ${roadmap?.nextTrigger!=null?`Reassess at ${m(roadmap.nextTrigger)} or on material fundamental evidence change.`:"Reassess when new decision-grade evidence arrives."}`;
 return{whyOwn,whatWorth,whereAccumulate,whatConfirms,whatBreaks,whatChanged,nextDecision};
}
