"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import SearchBox from "./SearchBox";
import {supabaseBrowser} from "@/lib/supabase";
import {ArrowUpRight,BriefcaseBusiness,Clock3,ShieldAlert,Sparkles,TrendingDown,TrendingUp} from "lucide-react";

type Mode="Best ideas"|"Strengthening"|"On sale"|"Risk / avoid";
const tone=(x:any)=>String(x?.action||"").includes("BUY")||x?.action==="ACCUMULATE"?"good":String(x?.action||"").includes("REDUCE")||String(x?.action||"").includes("EXIT")||x?.action==="AVOID"||x?.thesisLabel==="BEARISH"?"bad":"mid";

export default function InvestorRadarClient(){
 const[market,setMarket]=useState<any>(null),[ideas,setIdeas]=useState<any[]>([]),[changes,setChanges]=useState<any[]>([]),[portfolio,setPortfolio]=useState<any[]>([]),[coverage,setCoverage]=useState<any>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<Mode>("Best ideas");
 useEffect(()=>{let alive=true;(async()=>{
   try{
    const [m,d,t]=await Promise.all([fetch("/api/market").then(r=>r.json()).catch(()=>null),fetch("/api/discover?mode=discover&limit=80").then(r=>r.json()).catch(()=>({items:[]})),fetch("/api/discover?mode=today&limit=20").then(r=>r.json()).catch(()=>({items:[]}))]);
    if(!alive)return;setMarket(m);setIdeas(d.items||[]);setChanges(t.items||[]);setCoverage(d.coverage||null);
    const s=supabaseBrowser(),{data:{session}}=await s.auth.getSession();if(!session?.user)return;
    const[{data:p},{data:w}]=await Promise.all([s.from("portfolio_positions").select("symbol").eq("user_id",session.user.id),s.from("watchlist_items").select("symbol").eq("user_id",session.user.id)]);
    const syms=[...new Set([...(p||[]).map((x:any)=>x.symbol),...(w||[]).map((x:any)=>x.symbol)])].slice(0,40);
    if(syms.length){const x=await fetch(`/api/investment?symbols=${encodeURIComponent(syms.join(","))}`).then(r=>r.json()).catch(()=>({items:[]}));if(alive)setPortfolio(x.items||[])}
   }finally{if(alive)setLoading(false)}
 })();return()=>{alive=false}},[]);
 const filtered=useMemo(()=>ideas.filter(x=>mode==="Strengthening"?x.thesisState==="Strengthening":mode==="On sale"?x.valuationScore>=65&&x.thesisScore>=58:mode==="Risk / avoid"?tone(x)==="bad":tone(x)!=="bad").sort((a,b)=>{
   const ra=(a.opportunityScore*.40+a.thesisScore*.28+a.companyScore*.20+a.confidence*.12)-(a.thesisLabel==="BEARISH"?18:0),rb=(b.opportunityScore*.40+b.thesisScore*.28+b.companyScore*.20+b.confidence*.12)-(b.thesisLabel==="BEARISH"?18:0);return rb-ra
 }),[ideas,mode]);
 const coverageLine=coverage?.scanned?`${Number(coverage.scanned).toLocaleString()} companies modeled · ${Number(coverage.fresh48h||0).toLocaleString()} refreshed in 48h${coverage.fullMarket?" · broad coverage":" · coverage expanding"}`:"Investment scanner has not produced its first thesis records yet.";
 return <div className="v51RadarPage">
  <section className="v51Hero"><div><small>NIVORA RADAR</small><h1>Your holdings first. The market second.</h1><p>One place for thesis changes, portfolio risk and genuinely interesting long-horizon opportunities. No forced daily trade list.</p></div><SearchBox large/></section>
  <section className="v51Market"><div><small>MARKET REGIME</small><b className={market?.regime==="Risk-on"?"good":market?.regime==="Risk-off"?"bad":"mid"}>{market?.regime||"Loading"}</b><span>Used as a sizing/risk overlay—not as a company thesis.</span></div><div>{market?.items?.slice(0,4).map((x:any)=><Link href={`/stock/${encodeURIComponent(x.symbol)}`} key={x.symbol}><span>{x.symbol}</span><b className={x.changePct>=0?"good":"bad"}>{x.changePct>=0?"+":""}{x.changePct}%</b></Link>)}</div></section>
  <section className="v51Panel"><header><div><small><BriefcaseBusiness size={14}/> YOUR MONEY</small><h2>Portfolio & watchlist pulse</h2><p>NIVORA background scanning prioritizes symbols you own or explicitly follow.</p></div><Link href="/portfolio">Manage portfolio →</Link></header>{loading?<div className="softSkeleton">Loading your priority universe…</div>:portfolio.length?<div className="v51Cards">{portfolio.slice(0,8).map(x=><Link href={`/stock/${encodeURIComponent(x.symbol)}`} key={x.symbol}><div><b>{x.symbol}</b><span>{x.thesisState} thesis</span></div><strong className={tone(x)}>{x.action}</strong><small>Thesis {x.thesisScore} · Opportunity {x.opportunityScore}</small><ArrowUpRight size={15}/></Link>)}</div>:<div className="v51Empty"><Sparkles size={20}/><b>Your tracked names are being prioritized</b><span>If this is a new scanner install, run NIVORA Market Scanner once. Portfolio/watchlist symbols are scanned before the broad market.</span></div>}</section>
  <section className="v51Panel"><header><div><small><Clock3 size={14}/> WHAT CHANGED</small><h2>Only changes that can matter to capital</h2><p>Thesis/action changes are compared with prior stored observations. A red or green day alone is not a thesis change.</p></div></header>{changes.length?<div className="v51ChangeList">{changes.slice(0,8).map(x=><Link href={`/stock/${encodeURIComponent(x.symbol)}`} key={x.symbol}><b>{x.symbol}</b><strong className={tone(x)}>{x.action}</strong><span>{x.reason}</span><small>{x.previousThesisScore!=null?`Thesis ${x.previousThesisScore} → ${x.thesisScore}`:`Thesis ${x.thesisScore}`}</small></Link>)}</div>:<div className="v51Quiet"><b>No material thesis/action changes yet.</b><span>This stays quiet when nothing meaningful changed. Current opportunities are below.</span></div>}</section>
  <section className="v51Panel"><header><div><small><TrendingUp size={14}/> MARKET OPPORTUNITY ENGINE</small><h2>Best ideas from completed thesis coverage</h2><p>Ranked by company quality, forward thesis, valuation/opportunity and evidence confidence—not ticker order.</p><span className="v51Coverage">{coverageLine}</span></div></header><div className="v51Filters">{(["Best ideas","Strengthening","On sale","Risk / avoid"] as Mode[]).map(x=><button key={x} className={mode===x?"on":""} onClick={()=>setMode(x)}>{x}</button>)}</div>{filtered.length?<div className="v51RankList">{filtered.slice(0,20).map((x:any,i:number)=><Link href={`/stock/${encodeURIComponent(x.symbol)}`} key={x.symbol}><i>{i+1}</i><div><b>{x.symbol}</b><span>{x.thesisLabel} · {x.thesisState}</span></div><strong className={tone(x)}>{x.action}</strong><div><small>COMPANY</small><b>{x.companyScore}</b></div><div><small>THESIS</small><b>{x.thesisScore}</b></div><div><small>OPPORTUNITY</small><b>{x.opportunityScore}</b></div><div><small>EVIDENCE</small><b>{x.confidence}%</b></div><ArrowUpRight size={16}/></Link>)}</div>:<div className="v51Empty"><ShieldAlert size={20}/><b>{coverage?.scanned?"No names match this lens yet":"Scanner has zero completed thesis records"}</b><span>{coverage?.diagnostic||"Deploy the investment migration and run NIVORA Market Scanner. Priority portfolio/watchlist names will populate first; broad-market coverage follows without alphabetical leakage."}</span></div>}</section>
 </div>
}
