"use client";
import {useEffect,useMemo,useState} from "react";
import SearchBox from "./SearchBox";import PriceChart from "./PriceChart";
import {Star,ChevronDown,ExternalLink,Info,BriefcaseBusiness,Newspaper,CalendarDays,Activity,ShieldCheck,ArrowRight,PlusCircle} from "lucide-react";
import {supabaseBrowser} from "@/lib/supabase";import Link from "next/link";
type Mode="now"|"swing"|"long"|"own";type Tab="overview"|"fundamentals"|"catalysts"|"news"|"earnings"|"technical";
const tone=(s:string)=>{const x=(s||"").toUpperCase();if(x.includes("BUY")||x.includes("CONSTRUCTIVE")||x.includes("HOLD")||x.includes("STRONG"))return"good";if(x.includes("CHASE")||x.includes("AVOID")||x.includes("REDUCE")||x.includes("NOT YET")||x.includes("WEAK"))return"bad";return"mid"};
const money=(n:any)=>{const x=Number(n);if(!Number.isFinite(x))return String(n??"—");const a=Math.abs(x);return `${x<0?"-":""}$${a>=1e9?(a/1e9).toFixed(2)+"B":a>=1e6?(a/1e6).toFixed(1)+"M":a>=1e3?(a/1e3).toFixed(1)+"K":a.toLocaleString()}`};
const eps=(n:any)=>{const x=Number(n);return Number.isFinite(x)?`${x<0?"-":""}$${Math.abs(x).toFixed(2)}`:"—"};
const daysUntil=(d?:string|null)=>{if(!d)return null;return Math.ceil((new Date(d+"T12:00:00").getTime()-Date.now())/86400000)};
export default function StockClient({symbol}:{symbol:string}){
 const[d,setD]=useState<any>(null),[company,setCompany]=useState<any>(null),[context,setContext]=useState<any>(null),[err,setErr]=useState(""),[mode,setMode]=useState<Mode>("now"),[tab,setTab]=useState<Tab>("overview"),[technical,setTechnical]=useState(false),[watching,setWatching]=useState(false);
 useEffect(()=>{let live=true;let core:AbortController|null=null;
  const loadCore=async(initial=false)=>{if(initial){setD(null);setCompany(null);setContext(null);setErr("")}core?.abort();core=new AbortController();const timer=setTimeout(()=>core?.abort(),6500);try{const r=await fetch(`/api/analyze/${encodeURIComponent(symbol)}`,{signal:core.signal,cache:"no-store"});const a=await r.json();if(!r.ok||a.error)throw new Error(a.error||"Analysis unavailable");if(!live)return;setD(a);if(initial){Promise.allSettled([fetch(`/api/company/${encodeURIComponent(symbol)}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>live&&x&&setCompany(x)),fetch(`/api/context/${encodeURIComponent(symbol)}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>live&&x&&setContext(x))])}}catch(e:any){if(initial&&live)setErr(e.name==="AbortError"?"Market data is taking too long. Try again.":e.message)}finally{clearTimeout(timer)}};
  const loadContext=()=>fetch(`/api/context/${encodeURIComponent(symbol)}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>live&&x&&setContext(x)).catch(()=>{});
  loadCore(true);
  const priceTimer=setInterval(()=>{if(document.visibilityState==="visible")loadCore(false)},30000);
  const newsTimer=setInterval(()=>{if(document.visibilityState==="visible")loadContext()},120000);
  const onFocus=()=>{loadCore(false);loadContext()}; window.addEventListener("focus",onFocus);
  return()=>{live=false;core?.abort();clearInterval(priceTimer);clearInterval(newsTimer);window.removeEventListener("focus",onFocus)}},[symbol]);
 async function watch(){const s=supabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user)return;let{data:w}=await s.from("watchlists").select("id").eq("user_id",user.id).limit(1).maybeSingle();if(!w){const x=await s.from("watchlists").insert({user_id:user.id,name:"My Watchlist"}).select("id").single();w=x.data}if(w){await s.from("watchlist_items").upsert({watchlist_id:w.id,user_id:user.id,symbol},{onConflict:"watchlist_id,symbol"});setWatching(true)}}
 const view=useMemo(()=>{if(!d)return null;if(mode==="now")return d.views.today;if(mode==="swing")return d.views.swing;if(mode==="own")return d.views.own;const f=company?.fundamentalSignal;if(f?.label==="Strong"&&d.scores.trend>=45)return{label:"ATTRACTIVE / WATCH ENTRY",tone:"good",text:"Business quality looks strong. Use price weakness selectively rather than chasing; valuation and catalysts still matter."};if(f?.label?.includes("Weak"))return{label:"RESEARCH BEFORE BUYING",tone:"bad",text:"The business-quality signals are weak or mixed enough that a lower price alone is not a reason to buy."};return d.views.longTerm},[d,mode,company]);
 if(err)return <div className="osError"><b>Couldn’t analyze {symbol}</b><span>{err}</span><button onClick={()=>location.reload()}>Try again</button></div>;
 if(!d||!view)return <div className="osStockLoading"><div className="osLogo">NIVORA<span>.</span></div><b>Analyzing {symbol}</b><span>Building the decision first. Evidence loads after.</span></div>;
 const business=company?.fundamentalSignal||{label:d.assetType==="crypto"?"Crypto":"Loading",tone:"neutral",reasons:[]},news=context?.summary||{label:context?.enabled===false?"Feed not connected":"Loading",tone:"neutral",topReason:""},earn=context?.earnings,earnDays=daysUntil(earn?.date),filings=company?.filings||[],items=context?.news||[],latestEarnNews=context?.latestEarningsNews,latestReport=latestEarnNews||filings.find((f:any)=>["10-K","10-Q","20-F","6-K"].includes(f.form));
 const catalystLabel=earn?`Earnings ${earnDays!=null&&earnDays>=0?`in ${earnDays}d`:earn.date}`:company?.filingRisk?"Financing watch":filings[0]?filings[0].label:"None found";
 const changeAbs=Math.abs(d.changePct);const topNews=items.find((x:any)=>x.materiality==="High")||items[0];const moveReason=topNews?topNews.headline:changeAbs>=4?"No single material headline was identified yet. Treat the move as price/volume-driven until new evidence appears.":"No unusual move requiring a specific headline explanation was detected.";
 const positive=[...(business?.tone==="good"?(business.reasons||[]).slice(0,2):[]),...(d.positives||[])].filter(Boolean).slice(0,3);
 const risks=[...(company?.filingRisk?[company.filingRisk.label]:[]),...(news.tone==="negative"?[news.topReason]:[]),...(d.risks||[])].filter(Boolean).slice(0,3);
 const five=company?.fiveYearRecord; const businessScore=Number(business?.score??50); const sixScore=Number(d.sixMonth?.score??50); const timingScore=Number(d.scores?.entry??50); const riskScore=Number(d.scores?.risk??50);
 const overallScore=Math.max(0,Math.min(100,Math.round(businessScore*.38+sixScore*.22+timingScore*.25+(100-riskScore)*.15)));
 const overallLabel=overallScore>=78?"High-quality setup":overallScore>=62?"Promising / selective":overallScore>=48?"Mixed / wait":"Weak setup";
 const beginnerReason=view.label.includes("BUY")?"The evidence is strong enough to consider a disciplined entry at the mapped price levels.":view.label.includes("HOLD")?"If you already own it, the current evidence does not require an immediate exit, but the risk levels still matter.":"The stock may still be a good company, but today is not a strong enough entry yet.";
 return <div className="osStock v12Stock">
  <div className="osStockSearch"><SearchBox/></div>
  <header className="osStockHead v12StockHead"><div><small>{company?.name||d.name||symbol}</small><h1>{symbol}</h1></div><div><b>${d.price}</b><span className={d.changePct>=0?"up":"down"}>{d.changePct>=0?"+":""}{d.changePct}%</span></div></header>
  <div className="liveFresh"><span className="liveDot"/>Near-live decision · shared cache <small>Price/decision refreshes about every 30–45 sec while this page is open. News refreshes about every 2 min.</small></div>
  <div className="osMode v12Mode"><button className={mode==="now"?"on":""} onClick={()=>setMode("now")}>Now</button><button className={mode==="swing"?"on":""} onClick={()=>setMode("swing")}>Swing</button><button className={mode==="long"?"on":""} onClick={()=>setMode("long")}>Long term</button><button className={mode==="own"?"on":""} onClick={()=>setMode("own")}>I own it</button></div>
  <section className="beginnerScore"><div className="beginnerScoreMain"><small>IF YOU READ ONLY ONE THING</small><div className="scoreLine"><b>{overallScore}</b><span>/100</span><em>{overallLabel}</em></div><h3>{view.label}</h3><p>{beginnerReason}</p></div><div className="beginnerMath"><div><small>BUSINESS</small><b>{business.label}</b><span>{five?`${five.years}-year record · ${five.revenueTrend}`:"Loading financial history"}</span></div><div><small>6-MONTH CHART</small><b>{d.sixMonth?.label||"Mixed"}</b><span>{d.sixMonth?`${d.sixMonth.returnPct>=0?"+":""}${d.sixMonth.returnPct}% return":"Price history"}</span></div><div><small>TIMING NOW</small><b>{d.labels.entry}</b><span>Entry quality at today’s price.</span></div><div><small>RISK</small><b>{d.labels.risk}</b><span>Higher risk means use more caution.</span></div></div></section>
  <section className={`osDecision ${tone(view.label)} v12Decision`}><div className="osDecisionTop"><small>THE CALL</small><h2>{view.label}</h2><p>{view.text}</p></div><div className="osPlanGrid"><div><small>BETTER ENTRY</small><b>${d.levels.preferredEntry}–${d.levels.support}</b><span>Prefer stabilization in this area rather than buying simply because price is falling.</span></div><div><small>CONFIRMATION</small><b>Above ${d.levels.breakout}</b><span>Prefer a strong close or breakout retest with improving volume/momentum — not the first spike.</span></div><div><small>PROTECT / REASSESS</small><b>Below ${d.levels.invalidation}</b><span>Technical thesis weakens here. Recheck fundamentals and catalyst risk before deciding what to do.</span></div></div></section>
  <section className="v12QuickRead"><div><small>BUSINESS</small><b className={tone(business.label)}>{business.label}</b><span>{business.reasons?.[0]||"Fundamental evidence is loading."}</span></div><div><small>TREND</small><b className={tone(d.labels.trend)}>{d.labels.trend}</b><span>Direction and structure.</span></div><div><small>MOMENTUM</small><b className={tone(d.labels.momentum)}>{d.labels.momentum}</b><span>Speed and confirmation of the move.</span></div><div><small>ENTRY</small><b className={tone(d.labels.entry)}>{d.labels.entry}</b><span>How attractive today’s price is.</span></div><div><small>RISK</small><b className={d.labels.risk==="High"?"bad":d.labels.risk==="Lower"?"good":"mid"}>{d.labels.risk}</b><span>Volatility, extension and downside.</span></div><div><small>CATALYST</small><b className={company?.filingRisk?"bad":earn?"mid":"good"}>{catalystLabel}</b><span>{news.label}</span></div></section>
  <div className="osMicroActions v12Actions"><button onClick={watch}><Star size={16} fill={watching?"currentColor":"none"}/>{watching?"Watching":"Add to watchlist"}</button><Link href={`/portfolio?symbol=${encodeURIComponent(symbol)}`}><PlusCircle size={16}/>Track position</Link><span>Support ${d.levels.support}</span><span>Resistance ${d.levels.resistance}</span></div>
  <section className="v12ReasonGrid"><div className="v12Reason goodBox"><small>WHY IT CAN WORK</small><h3>What supports the setup</h3>{positive.length?positive.map((x:string,i:number)=><p key={i}>✓ {x}</p>):<p>Evidence is still loading or mixed.</p>}</div><div className="v12Reason riskBox"><small>WHAT CAN GO WRONG</small><h3>What is holding it back</h3>{risks.length?risks.map((x:string,i:number)=><p key={i}>• {x}</p>):<p>No major risk flag was detected from the connected sources.</p>}</div></section>
  <section className="v12Pulse"><div><small>WHAT CHANGED TODAY</small><h3>{changeAbs>=4?`Large ${d.changePct>=0?"move up":"move down"}: ${d.changePct>=0?"+":""}${d.changePct}%`:"Today’s move"}</h3><p>{moveReason}</p>{topNews?.url&&<a href={topNews.url} target="_blank" rel="noreferrer">Read source <ExternalLink size={13}/></a>}</div><div><small>NEXT CATALYST</small><h3>{earn?`Earnings · ${earn.date}`:filings[0]?.label||"No scheduled catalyst found"}</h3><p>{earn?`${earn.hour||"Timing not listed"}${earn.epsEstimate!=null?` · EPS est. ${earn.epsEstimate}`:""}`:filings[0]?`${filings[0].form} filed ${filings[0].date}`:"NIVORA will surface a catalyst when a connected source identifies one."}</p></div><div><small>MARKET CONTEXT</small><h3>{d.market.regime}</h3><p>{d.market.benchmark?`${symbol} is ${d.market.relativeStrength.toLowerCase()} versus ${d.market.benchmark} over the recent period.`:"Crypto benchmark context is handled separately."}</p></div></section>
  <section className="osChartCard v12Chart"><div className="osSectionTitle"><div><small>PRICE MAP</small><h3>What price has to do next</h3></div><span>Green = entry/support · Orange = confirmation · Red = reassess</span></div><PriceChart candles={d.candles} levels={d.levels}/></section>
  <section className="osContext v12Context"><div className="osTabs v12Tabs"><button className={tab==="overview"?"on":""} onClick={()=>setTab("overview")}>Overview</button><button className={tab==="fundamentals"?"on":""} onClick={()=>setTab("fundamentals")}>Fundamentals</button><button className={tab==="catalysts"?"on":""} onClick={()=>setTab("catalysts")}>Catalysts</button><button className={tab==="news"?"on":""} onClick={()=>setTab("news")}>News</button><button className={tab==="earnings"?"on":""} onClick={()=>setTab("earnings")}>Earnings</button><button className={tab==="technical"?"on":""} onClick={()=>setTab("technical")}>Technical</button></div>
   {tab==="overview"&&<div className="v12Overview"><div><BriefcaseBusiness size={18}/><small>Business</small><b className={tone(business.label)}>{business.label}</b><span>{business.reasons?.[0]||"Loading fundamentals…"}</span></div><div><Activity size={18}/><small>Entry</small><b className={tone(d.labels.entry)}>{d.labels.entry}</b><span>Current location versus support, extension and momentum.</span></div><div><ShieldCheck size={18}/><small>Risk</small><b className={d.labels.risk==="High"?"bad":"mid"}>{d.labels.risk}</b><span>Technical downside plus market regime.</span></div><div><Newspaper size={18}/><small>News</small><b className={news.tone==="positive"?"good":news.tone==="negative"?"bad":"mid"}>{news.label}</b><span>{news.topReason}</span></div></div>}
   {tab==="fundamentals"&&<div className="v12Fund"><div className={`fundSignal ${business.tone||"neutral"}`}><small>BUSINESS QUALITY</small><h3>{business.label}{business.score!=null?` · ${business.score}/100`:""}</h3>{(business.reasons||[]).slice(0,4).map((x:string,i:number)=><p key={i}>• {x}</p>)}{five&&<div className="fiveRecord"><small>5-YEAR RECORD</small><b>{five.score}/100 · {five.revenueTrend}</b><p>{five.summary}</p><div>{(five.history||[]).map((y:any)=><span key={y.year}><i>{y.year}</i><strong>{y.revenue!=null?money(y.revenue):"—"}</strong><em>{y.netIncome!=null?`NI ${money(y.netIncome)}`:"NI —"}</em></span>)}</div></div>}</div><div className="osList">{company?.fundamentals?.length?company.fundamentals.map((x:any)=><div key={x.label}><span>{x.label}{x.detail&&<small>{x.detail}</small>}</span><b>{x.value}</b></div>):<p>No standardized SEC fundamentals available for this symbol yet.</p>}</div></div>}
   {tab==="catalysts"&&<div className="v12Catalysts">{earn&&<div className="nextEvent"><CalendarDays size={18}/><div><small>NEXT EARNINGS</small><b>{earn.date}</b><span>{earnDays!=null&&earnDays>=0?`${earnDays} days away`:"Upcoming"}</span></div></div>}<div className="osList links">{filings.length?filings.slice(0,8).map((x:any)=><a href={x.url} target="_blank" rel="noreferrer" key={x.accession}><span><b>{x.label}</b><small>{x.form} · {x.description}</small></span><em className={x.tone}>{x.materiality}</em><small>{x.date}</small><ExternalLink size={13}/></a>):<p>No recent material SEC filings found.</p>}</div></div>}
   {tab==="news"&&<div className="v12News">{context?.enabled===false?<div className="connectFeed"><Newspaper size={22}/><b>Connect live news</b><p>Add a free Finnhub API key to `.env.local`. Price analysis and SEC data continue to work without it.</p></div>:items.length?items.map((x:any,i:number)=><a href={x.url} target="_blank" rel="noreferrer" key={i}><div><span className={`newsTone ${x.tone}`}>{x.tone}</span><small>{x.materiality} materiality · {x.source}</small></div><b>{x.headline}</b><p>{x.summary}</p><ExternalLink size={13}/></a>):<p>No recent company headlines were returned.</p>}</div>}
   {tab==="earnings"&&<div className="v12Earnings"><div className="earnSplit">{latestReport&&<div className="earnNext earnReported"><small>LATEST REPORTED RESULTS</small><h3>{latestEarnNews?.date?new Date(latestEarnNews.date).toLocaleDateString():latestReport.date}</h3><p>{latestEarnNews?.headline||`${latestReport.form} filed — latest reported financial filing`}</p>{latestEarnNews?.url&&<a href={latestEarnNews.url} target="_blank" rel="noreferrer">Read results <ExternalLink size={12}/></a>}</div>}{earn&&<div className="earnNext estimated"><small>NEXT EARNINGS · ESTIMATED</small><h3>{earn.date}</h3><p>{earn.hour||"Time not listed"}{earn.epsEstimate!=null?` · EPS est. ${eps(earn.epsEstimate)}`:""}{earn.revenueEstimate!=null?` · Revenue est. ${money(earn.revenueEstimate)}`:""}</p><p className="earnMeta">Future calendar dates are estimates until confirmed by the company.</p></div>}</div><div className="earnGrid">{(context?.surprises||[]).length?context.surprises.map((x:any,i:number)=><div key={i}><small>{x.period}</small><b className={(x.surprisePercent??0)>=0?"good":"bad"}>{x.surprisePercent!=null?`${x.surprisePercent>=0?"+":""}${Number(x.surprisePercent).toFixed(1)}% surprise`:"Reported"}</b><span>Actual {x.actual??"—"} · Est. {x.estimate??"—"}</span></div>):<p>No earnings-surprise history returned by the connected feed.</p>}</div></div>}
   {tab==="technical"&&<div className="v12Technical"><div className="techIntro"><h3>Technical evidence</h3><p>You do not need these numbers to use NIVORA. They are the evidence underneath the plain-English call.</p></div><div className="osTechGrid">{Object.entries(d.engine).map(([k,v]:any)=><div key={k}><span>{k}<Info size={12}/></span><b>{typeof v==="number"?`${v}/100`:v}</b></div>)}</div><div className="techWhy">{d.why.map((x:string,i:number)=><p key={i}>• {x}</p>)}</div></div>}
  </section>
  <div className="osDisclaimer">NIVORA is decision support, not a guarantee. The call should change when price, fundamentals, catalysts or risk change. <Link href="/disclaimer">Read disclaimer</Link></div>
 </div>
}
