"use client";
import {useEffect,useState} from "react";import Link from "next/link";import SearchBox from "./SearchBox";import {supabaseBrowser} from "@/lib/supabase";import {ArrowUpRight,Activity,Eye,ShieldAlert,Zap} from "lucide-react";
export default function TodayClient(){const[market,setMarket]=useState<any>(null),[scan,setScan]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;fetch("/api/market").then(r=>r.json()).then(x=>alive&&setMarket(x)).catch(()=>{});(async()=>{try{const s=supabaseBrowser();const{data:{session}}=await s.auth.getSession();const user=session?.user;if(!user)return;const{data}=await s.from("watchlist_items").select("symbol").eq("user_id",user.id).limit(8);const syms=(data||[]).map((x:any)=>x.symbol);if(syms.length){const x=await fetch(`/api/scan?symbols=${encodeURIComponent(syms.join(","))}`).then(r=>r.json());if(alive)setScan(x.items||[])}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 return <div className="todayPage"><section className="todayHero"><div><div className="eyebrow">YOUR DAILY INVESTOR OS</div><h1>What deserves attention today?</h1><p>Search anything, or start with the names you already follow.</p></div><SearchBox large/></section>
 <section className="marketStrip"><div className="marketRegime"><small>MARKET REGIME</small><b className={market?.regime==="Risk-on"?"good":market?.regime==="Risk-off"?"bad":"mid"}>{market?.regime||"Loading…"}</b><span>Broad-market context changes how aggressive new entries should be.</span></div><div className="marketTiles">{market?.items?.map((x:any)=><Link key={x.symbol} href={`/stock/${encodeURIComponent(x.symbol)}`}><span>{x.symbol}</span><b className={x.changePct>=0?"good":"bad"}>{x.changePct>=0?"+":""}{x.changePct}%</b><small>{x.trend}</small></Link>)}</div></section>
 <section className="todayGrid"><div className="todayCard attention"><div className="todayTitle"><div><small>YOUR WATCHLIST</small><h2>Needs attention</h2></div><Link href="/watchlist">View all →</Link></div>{loading?<div className="softSkeleton">Checking your watchlist…</div>:scan.length?scan.slice(0,6).map((x:any)=><Link className="scanRow" key={x.symbol} href={`/stock/${encodeURIComponent(x.symbol)}`}><div><b>{x.symbol}</b><span>{x.reason}</span></div><div><strong className={x.action.includes("READY")?"good":x.action.includes("CHASE")?"bad":"mid"}>{x.action}</strong><small>${x.price} · {x.changePct>=0?"+":""}{x.changePct}%</small></div></Link>):<div className="emptyToday"><Eye size={21}/><b>Your watchlist is empty</b><span>Add stocks you care about. NIVORA will rank what needs attention here.</span><Link href="/analyze">Analyze a stock →</Link></div>}</div>
 <div className="todayCard playbook"><div className="todayTitle"><div><small>QUICK START</small><h2>Find a setup</h2></div></div><Link href="/analyze"><Zap size={18}/><div><b>Quality pullback</b><span>Strong asset returning toward a better price.</span></div><ArrowUpRight size={16}/></Link><Link href="/analyze"><Activity size={18}/><div><b>Early momentum</b><span>Improving trend + momentum before it gets stretched.</span></div><ArrowUpRight size={16}/></Link><Link href="/stock/SPY"><ShieldAlert size={18}/><div><b>Market check</b><span>Know whether the market is helping or hurting new risk.</span></div><ArrowUpRight size={16}/></Link></div></section>
 </div>}
