export type MetricDefinition={title:string;short:string;uses:string;freshness:string;source:string};
export const metricDefinitions:Record<string,MetricDefinition>={
 business:{title:"Business quality",short:"Durability and quality of the underlying company, independent of today's share price.",uses:"Revenue quality, financial strength, margins, cash generation, multi-year record and archetype-specific evidence.",freshness:"Moves slowly; refreshed when company evidence changes.",source:"Company fundamentals / filings / normalized evidence."},
 financial:{title:"Financial strength",short:"Balance-sheet resilience and the quality of cash economics.",uses:"Free cash flow, operating margin, gross margin and leverage evidence available to NIVORA.",freshness:"Primarily filing-driven.",source:"Fundamental filings and normalized company metrics."},
 growth:{title:"Growth",short:"Current and multi-year revenue/profit growth evidence.",uses:"Revenue growth, profit growth and the company's multi-year growth trend.",freshness:"Changes with reported and forward business evidence.",source:"Company fundamentals and historical records."},
 durability:{title:"Durability",short:"How repeatable the business economics appear across time.",uses:"Five-year evidence, business quality and financial resilience.",freshness:"Designed to move slowly.",source:"Historical company evidence."},
 forward:{title:"Forward thesis",short:"Whether the evidence about the next several reporting periods is improving or deteriorating.",uses:"Growth, earnings evidence, Street changes and catalysts. Raw Buy ratings are deliberately low-weight.",freshness:"Refreshes when forward evidence changes.",source:"Earnings, analyst-change and catalyst feeds."},
 earnings:{title:"Earnings evidence",short:"Recent execution versus expectations, with greater weight on newer reports.",uses:"Recent reported surprise history. It is supporting evidence, not the entire thesis.",freshness:"Updates after reported earnings.",source:"Connected earnings feed."},
 streetChange:{title:"Street change",short:"Direction of analyst opinion, not the absolute Buy/Hold/Sell level.",uses:"Recent change in recommendation consensus. NIVORA treats change as more informative than the structurally bullish raw level.",freshness:"Updates when analyst recommendation history changes.",source:"Connected analyst recommendation feed."},
 institutional:{title:"Institutional evidence",short:"Delayed reported ownership behavior from institutional filings.",uses:"Quarter-over-quarter ownership changes and manager breadth. It never represents real-time buying.",freshness:"Quarterly / filing-lagged.",source:"SEC 13F-derived evidence."},
 catalysts:{title:"Catalysts",short:"Material events that can change the investment case.",uses:"News tone, filings, scheduled events and identified financing/dilution risk.",freshness:"Event-driven.",source:"News / filing / event feeds."},
 valuation:{title:"NIVORA valuation",short:"Independent valuation evidence appropriate to the company's archetype.",uses:"Archetype-specific preliminary models. Missing valuation is N/A and does not count as bearish evidence.",freshness:"Changes with price and underlying valuation inputs.",source:"Fundamentals and archetype-specific model inputs."},
 timing:{title:"Entry timing",short:"How attractive today's execution setup is without changing the fundamental thesis.",uses:"Trend, momentum, participation, extension and entry structure.",freshness:"Market-data driven.",source:"Price/volume market data."},
 risk:{title:"Risk pressure",short:"Higher numbers mean more downside/volatility pressure, not greater safety.",uses:"Volatility, extension, technical downside and broad market pressure.",freshness:"Market-data driven.",source:"Price/volatility and market-regime evidence."},
 opportunity:{title:"Current opportunity",short:"How attractive new capital looks after combining thesis, valuation when available, risk and timing.",uses:"Weights are re-normalized when a factor is genuinely unavailable; missing data is uncertainty, not a zero score.",freshness:"Changes faster than the company thesis.",source:"Canonical NIVORA decision engine."},
 dataCoverage:{title:"Data coverage",short:"How many required evidence families are currently available.",uses:"Coverage is not probability of profit and is not model accuracy.",freshness:"Changes with feed availability.",source:"NIVORA evidence availability checks."},
 modelReliability:{title:"Model reliability",short:"Historical reliability of comparable, versioned, benchmark-relative NIVORA calls.",uses:"Shown as collecting/uncalibrated until enough comparable outcomes mature.",freshness:"Updates as forward outcomes mature.",source:"Immutable decision/outcome calibration ledger."},
 street:{title:"Wall Street consensus",short:"External analyst opinion shown as context, not NIVORA valuation.",uses:"NIVORA may disagree and explains why when the evidence diverges.",freshness:"Updates with analyst coverage.",source:"Connected analyst recommendation feed."},
 priceMap:{title:"Price map",short:"Staged execution zones derived from independent valuation when available and structural market levels.",uses:"Fundamental zones guide expected-return entry; technical levels refine execution. They do not rewrite company quality.",freshness:"Valuation changes slowly; technical levels can change faster.",source:"NIVORA valuation + market structure."}
};
