export const ENGINE_VERSION="v61" as const;
export const WEIGHTS_VERSION="v59-thesis-1" as const;
export const VALUATION_VERSION="v59-archetype-3" as const;
export const TODAY_POLICY_VERSION="v60-live-today-1" as const;
export const SNAPSHOT_SCHEMA_VERSION="v59-snapshot-1" as const;
export const ARENA_SCHEMA_VERSION="v59-arena-1" as const;
export const LIVE_QUOTE_SCHEMA_VERSION="v60-live-quote-1" as const;
export const TRADING_LAB_VERSION="v61-trading-lab-1" as const;
export const RELIABILITY_MIN_SAMPLE=30;
