"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UX_SYSTEM_VERSION = exports.PORTFOLIO_VERSION = exports.BUY_CALIBRATION_VERSION = exports.CONSISTENCY_VERSION = exports.RELIABILITY_MIN_SAMPLE = exports.METRIC_PROOF_VERSION = exports.BACKTEST_VERSION = exports.TECHNICAL_ENGINE_VERSION = exports.MARKET_REALITY_VERSION = exports.CALIBRATION_VERSION = exports.DECISION_INTELLIGENCE_VERSION = exports.TRADING_LAB_VERSION = exports.LIVE_QUOTE_SCHEMA_VERSION = exports.ARENA_SCHEMA_VERSION = exports.SNAPSHOT_SCHEMA_VERSION = exports.TODAY_POLICY_VERSION = exports.VALUATION_VERSION = exports.WEIGHTS_VERSION = exports.ENGINE_VERSION = void 0;
exports.ENGINE_VERSION = "v65.2";
exports.WEIGHTS_VERSION = "v59-thesis-1";
exports.VALUATION_VERSION = "v65-valuation-proof-1";
exports.TODAY_POLICY_VERSION = "v65.2-decision-first-1";
exports.SNAPSHOT_SCHEMA_VERSION = "v65.2-snapshot-provenance-1";
exports.ARENA_SCHEMA_VERSION = "v65-validation-arena-1";
exports.LIVE_QUOTE_SCHEMA_VERSION = "v65-provider-consensus-1";
exports.TRADING_LAB_VERSION = "v65.7-paper-invalidation-1";
exports.DECISION_INTELLIGENCE_VERSION = "v65.2-slow-fast-decision-1";
exports.CALIBRATION_VERSION = "v65-champion-challenger-1";
exports.MARKET_REALITY_VERSION = "v65-market-reality-1";
exports.TECHNICAL_ENGINE_VERSION = "v64-wilder-technical-1";
exports.BACKTEST_VERSION = "v65.2-buy-path-backtest-1";
exports.METRIC_PROOF_VERSION = "v65-metric-proof-1";
exports.RELIABILITY_MIN_SAMPLE = 30;
exports.CONSISTENCY_VERSION = "v65.2-consistency-1";
exports.BUY_CALIBRATION_VERSION = "v65.2-starter-paths-1";
exports.PORTFOLIO_VERSION = "v65-multi-asset-1";
exports.UX_SYSTEM_VERSION = "v65.7-context-help-1";
