"use client";
import {useState} from 'react';
import type {GroundedEvidence} from '@/lib/auryn/v931/domain';

export default function AstraAnalystPanel({symbol,snapshotId,canonicalAction,evidence}:{symbol:string;snapshotId:string;canonicalAction:string;evidence:GroundedEvidence[]}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false);
 async function run(){setLoading(true);setData(null);try{const r=await fetch(`/api/astra/${encodeURIComponent(symbol)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({snapshotId,canonicalAction,evidence}),cache:'no-store'});setData(await r.json())}catch(e:any){setData({status:'unavailable',reason:e?.message||'Astra is unavailable.'})}finally{setLoading(false)}}
 const unavailableReason=data?.status==='grounded'?'':(/API[_ -]?KEY|not configured|credential/i.test(String(data?.reason||''))?'Analyst review is unavailable in this deployment. Deterministic AURYN remains active.':String(data?.reason||'Analyst review is unavailable in this deployment. Deterministic AURYN remains active.'));
 return <section className="v931Astra"><div className="v931AstraHead"><div><small>ASTRA ANALYST · GROUNDED CHALLENGER</small><b>Independent expert review</b><span>Astra challenges the same canonical evidence; it cannot alter price, levels, the call, sizing or execution permission.</span></div><button type="button" onClick={run} disabled={loading}>{loading?'Reviewing…':data?'Re-run review':'Run independent review'}</button></div>
  {data?.status==='grounded'?<div className="v931AstraBody"><p className="v931AstraSummary">{data.analysis.executiveSummary}</p><div><article><small>STRONGEST EVIDENCE</small>{data.analysis.strongestEvidence?.slice(0,3).map((x:string)=><p key={x}>{x}</p>)}</article><article><small>COUNTER-EVIDENCE</small>{data.analysis.strongestCounterEvidence?.slice(0,3).map((x:string)=><p key={x}>{x}</p>)}</article></div><div><article><small>NEW MONEY</small><p>{data.analysis.investorActionExplanation}</p></article><article><small>EXISTING OWNER</small><p>{data.analysis.ownerActionExplanation}</p></article></div>{data.analysis.contradictionFlags?.length?<div className="v931AstraFlags"><small>CHALLENGER FLAGS</small>{data.analysis.contradictionFlags.map((x:string)=><p key={x}>{x}</p>)}</div>:null}<small className="v931Grounded">Grounding validated · Snapshot {snapshotId}</small></div>:data?<div className="v931AstraUnavailable"><b>Independent analyst review unavailable.</b><span>{unavailableReason}</span></div>:null}
 </section>;
}
