import fs from 'node:fs';
import path from 'node:path';
const valueArg=n=>{const p=`--${n}=`;const a=process.argv.find(x=>x.startsWith(p));return a?a.slice(p.length):''};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const startDate=valueArg('start-date'),endDate=valueArg('end-date'),symbolsPath=valueArg('symbols'),outputPath=valueArg('output');
const benchmark=String(valueArg('benchmark')||'SPY').toUpperCase();
const tdKey=process.env.TWELVE_DATA_API_KEY||'',secUA=process.env.SEC_USER_AGENT||'',fredKey=process.env.FRED_API_KEY||'';
const skipSec=process.argv.includes('--skip-sec'),withCorporateActions=process.argv.includes('--with-corporate-actions'),withEarnings=process.argv.includes('--with-earnings');
const researchEventsPath=valueArg('research-events'),fredSeriesPath=valueArg('fred-series');
if(!startDate||!endDate||!symbolsPath||!outputPath)throw new Error('Usage: npm run backfill:v92 -- --symbols=/path/security-master.json --start-date=2016-01-01 --end-date=2026-09-08 --output=/path/replay.json [--benchmark=SPY] [--universe=/path/universe.json] [--with-corporate-actions] [--with-earnings] [--research-events=/path/events.json] [--fred-series=/path/series.json]');
if(!tdKey)throw new Error('TWELVE_DATA_API_KEY is required for V9.2 historical price backfill.');
if(!skipSec&&!secUA)throw new Error('SEC_USER_AGENT is required for SEC historical facts (example: YourApp contact@example.com). Use --skip-sec only when deliberately omitting fundamentals.');
if(fredSeriesPath&&!fredKey)throw new Error('FRED_API_KEY is required when --fred-series is supplied.');
const {buildTwelveDataDailyUrl,normalizeTwelveDataDaily}=await import('../.engine-test/auryn/v92/twelve-data.js');
const {normalizeAndDeriveSecCompanyFacts}=await import('../.engine-test/auryn/v92/sec-companyfacts.js');
const {buildTwelveDataSplitsUrl,buildTwelveDataDividendsUrl,normalizeTwelveDataSplits,normalizeTwelveDataDividends}=await import('../.engine-test/auryn/v92/corporate-actions.js');
const {buildTwelveDataEarningsUrl,normalizeTwelveDataEarnings,normalizePointInTimeResearchRows}=await import('../.engine-test/auryn/v92/research-events.js');
const {buildFredVintageUrl,normalizeFredVintageObservations}=await import('../.engine-test/auryn/v92/fred.js');
const {assembleHistoricalReplayBundle}=await import('../.engine-test/auryn/v92/assemble.js');
const {auditV92ReplayBundle}=await import('../.engine-test/auryn/v92/integrity.js');
const rawMaster=JSON.parse(fs.readFileSync(path.resolve(symbolsPath),'utf8'));const securities=(Array.isArray(rawMaster)?rawMaster:rawMaster.securities||[]).map(x=>({...x,symbol:String(x.symbol||'').toUpperCase()})).filter(x=>x.symbol);
if(!securities.length)throw new Error('Security master contains no symbols.');
const delayMs=Math.max(0,Number(valueArg('delay-ms')||process.env.AURYN_V92_TD_DELAY_MS||800));const secDelay=Math.max(100,Number(process.env.AURYN_V92_SEC_DELAY_MS||150));
async function fetchJson(url,{headers={},attempts=3,timeout=30000}={}){let last;for(let i=0;i<attempts;i++){try{const r=await fetch(url,{headers,signal:AbortSignal.timeout(timeout)});if(r.status===429||r.status===503){const ra=Number(r.headers.get('retry-after'));await sleep(Number.isFinite(ra)&&ra>0?ra*1000:Math.min(60000,1500*2**i));continue;}const j=await r.json();if(!r.ok)throw new Error(j?.message||`${r.status} ${r.statusText}`);return j;}catch(e){last=e;if(i<attempts-1)await sleep(Math.min(10000,1000*2**i));}}throw last;}
async function secTickerMap(){const j=await fetchJson('https://www.sec.gov/files/company_tickers.json',{headers:{'User-Agent':secUA,'Accept-Encoding':'gzip, deflate'},timeout:20000});const m=new Map();for(const x of Object.values(j||{}))if(x?.ticker&&x?.cik_str)m.set(String(x.ticker).toUpperCase(),Number(x.cik_str));return m;}
const coverage=new Map(),cover=(family,symbol)=>{const f=String(family).toUpperCase(),s=String(symbol).toUpperCase();const set=coverage.get(f)||new Set();set.add(s);coverage.set(f,set)};
const inDateRange=date=>String(date)>=startDate&&String(date)<=endDate;
const allSymbols=[...new Set([...securities.map(x=>x.symbol),benchmark])],dailyBars=[];let benchmarkBars=[];const coverageGaps=[];
for(let i=0;i<allSymbols.length;i++){const symbol=allSymbols[i];try{const url=buildTwelveDataDailyUrl({symbol,startDate,endDate,apiKey:tdKey});const j=await fetchJson(url,{attempts:4,timeout:45000});const n=normalizeTwelveDataDaily(symbol,j);if(symbol===benchmark)benchmarkBars=n.bars;else dailyBars.push(...n.bars);console.error(`[prices ${i+1}/${allSymbols.length}] ${symbol}: ${n.bars.length} bars`);}catch(e){coverageGaps.push({symbol,source:'TWELVE_DATA',error:String(e?.message||e)});console.error(`[prices ${i+1}/${allSymbols.length}] ${symbol}: GAP ${String(e?.message||e)}`);}if(delayMs)await sleep(delayMs);}
if(!benchmarkBars.length)throw new Error(`Benchmark ${benchmark} could not be backfilled; research labels cannot be constructed.`);
const facts=[];if(!skipSec){const map=await secTickerMap();for(let i=0;i<securities.length;i++){const sec=securities[i],cik=Number(sec.cik||map.get(sec.symbol));if(!Number.isFinite(cik)){coverageGaps.push({symbol:sec.symbol,source:'SEC',error:'CIK unavailable'});continue;}try{const u=`https://data.sec.gov/api/xbrl/companyfacts/CIK${String(cik).padStart(10,'0')}.json`;const j=await fetchJson(u,{headers:{'User-Agent':secUA,'Accept-Encoding':'gzip, deflate'},attempts:3,timeout:30000});const n=normalizeAndDeriveSecCompanyFacts(sec.symbol,j);facts.push(...n.all);cover('FUNDAMENTALS',sec.symbol);console.error(`[sec ${i+1}/${securities.length}] ${sec.symbol}: ${n.all.length} facts/derived metrics`);}catch(e){coverageGaps.push({symbol:sec.symbol,source:'SEC',error:String(e?.message||e)});console.error(`[sec ${i+1}/${securities.length}] ${sec.symbol}: GAP ${String(e?.message||e)}`);}await sleep(secDelay);}}
const corporateActions=[];
if(withCorporateActions){for(let i=0;i<securities.length;i++){const symbol=securities[i].symbol;try{const splits=await fetchJson(buildTwelveDataSplitsUrl({symbol,apiKey:tdKey}),{attempts:3,timeout:30000});if(delayMs)await sleep(delayMs);const dividends=await fetchJson(buildTwelveDataDividendsUrl({symbol,apiKey:tdKey,startDate,endDate}),{attempts:3,timeout:30000});corporateActions.push(...normalizeTwelveDataSplits(symbol,splits).filter(x=>inDateRange(x.date)),...normalizeTwelveDataDividends(symbol,dividends).filter(x=>inDateRange(x.date)));cover('CORPORATE_ACTIONS',symbol);console.error(`[actions ${i+1}/${securities.length}] ${symbol}: verified`);}catch(e){coverageGaps.push({symbol,source:'TWELVE_DATA_CORPORATE_ACTIONS',error:String(e?.message||e)});console.error(`[actions ${i+1}/${securities.length}] ${symbol}: GAP ${String(e?.message||e)}`);}if(delayMs)await sleep(delayMs);}}
const events=[];
if(withEarnings){for(let i=0;i<securities.length;i++){const symbol=securities[i].symbol;try{const j=await fetchJson(buildTwelveDataEarningsUrl({symbol,apiKey:tdKey}),{attempts:3,timeout:30000});events.push(...normalizeTwelveDataEarnings(symbol,j).filter(x=>x.availableAt<=endDate));cover('EARNINGS',symbol);console.error(`[earnings ${i+1}/${securities.length}] ${symbol}: verified`);}catch(e){coverageGaps.push({symbol,source:'TWELVE_DATA_EARNINGS',error:String(e?.message||e)});console.error(`[earnings ${i+1}/${securities.length}] ${symbol}: GAP ${String(e?.message||e)}`);}if(delayMs)await sleep(delayMs);}}
const inferCoverage=row=>{const symbol=String(row?.symbol||'').toUpperCase(),metric=String(row?.metric||''),family=String(row?.family||'').toUpperCase();if(family)cover(family,symbol);else{if(/revision/i.test(metric)||['estimate_dispersion','guidance_delta'].includes(metric))cover('REVISION',symbol);if(['sector_relative_strength','industry_breadth','peer_revision_breadth'].includes(metric))cover('SECTOR',symbol);if(symbol==='__MACRO__')cover('MACRO','__MACRO__');}};
if(researchEventsPath){const raw=JSON.parse(fs.readFileSync(path.resolve(researchEventsPath),'utf8')),rows=Array.isArray(raw)?raw:(raw.events||[]);events.push(...normalizePointInTimeResearchRows(rows).filter(x=>x.availableAt<=endDate));for(const row of rows)inferCoverage(row);}
if(fredSeriesPath){const raw=JSON.parse(fs.readFileSync(path.resolve(fredSeriesPath),'utf8')),series=Array.isArray(raw)?raw:(raw.series||[]);for(const [i,item] of series.entries()){try{const u=buildFredVintageUrl({seriesId:item.seriesId,apiKey:fredKey,observationStart:item.observationStart||startDate,observationEnd:item.observationEnd||endDate});const j=await fetchJson(u,{attempts:3,timeout:30000});events.push(...normalizeFredVintageObservations(item.seriesId,item.metric,j).filter(x=>x.availableAt<=endDate));cover('MACRO','__MACRO__');console.error(`[fred ${i+1}/${series.length}] ${item.seriesId}: verified`);}catch(e){coverageGaps.push({symbol:'__MACRO__',source:`FRED:${item.seriesId||'UNKNOWN'}`,error:String(e?.message||e)});console.error(`[fred ${i+1}/${series.length}] ${item.seriesId||'UNKNOWN'}: GAP ${String(e?.message||e)}`);}}}
let universe={};const universePath=valueArg('universe');if(universePath)universe=JSON.parse(fs.readFileSync(path.resolve(universePath),'utf8'));
if(Array.isArray(universe.events)&&universe.events.length){events.push(...normalizePointInTimeResearchRows(universe.events));for(const row of universe.events)inferCoverage(row);}
const adapterCoverage=Object.fromEntries([...coverage.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([family,symbols])=>[family,[...symbols].sort()]));
const sources=['TWELVE_DATA',...(skipSec?[]:['SEC']),...(withCorporateActions?['CORPORATE_ACTIONS']:[]),...(withEarnings?['EARNINGS']:[]),...(researchEventsPath?['PIT_RESEARCH']:[]),...(fredSeriesPath?['FRED_VINTAGES']:[])];
const bundle=assembleHistoricalReplayBundle({datasetId:valueArg('dataset-id')||`auryn-v92-${startDate}-${endDate}`,version:'1',source:sources.join('+'),benchmarkSymbol:benchmark,generatedAt:new Date().toISOString(),securities,dailyBars,benchmarkBars,facts,events,corporateActions,adapterCoverage,universeSnapshots:Array.isArray(universe.universeSnapshots)?universe.universeSnapshots:[],pointInTimeUniverse:universe.pointInTimeUniverse===true,includesDelisted:universe.includesDelisted===true,delistingReturnsHandled:universe.delistingReturnsHandled===true});
const report=auditV92ReplayBundle(bundle);const out=path.resolve(outputPath);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(bundle,null,2)+'\n');fs.writeFileSync(`${out}.v92-audit.json`,JSON.stringify({...report,coverageGaps},null,2)+'\n');
console.log(JSON.stringify({version:report.version,state:'BACKFILL_COMPLETE',output:out,status:report.status,quality:report.quality,coverage:report.coverage,coverageGaps:coverageGaps.length,note:'Backfill output is research-only. Production CIO weights and broker permissions are unchanged.'},null,2));if(report.status==='BLOCKED')process.exitCode=1;
