import fs from 'node:fs';
import path from 'node:path';
const valueArg=(name)=>{const p=`--${name}=`;const a=process.argv.find(x=>x.startsWith(p));return a?a.slice(p.length):'';};
const readJsonOrJsonl=(file)=>{const text=fs.readFileSync(file,'utf8').trim();if(!text)return[];if(text.startsWith('['))return JSON.parse(text);return text.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));};
const basePath=valueArg('base')||process.env.AURYN_V91_BASE_OBSERVATIONS||'';
const outputPath=valueArg('output')||process.env.AURYN_V91_FEATURE_OBSERVATIONS||'';
if(!basePath||!outputPath)throw new Error('Usage: npm run materialize:v91 -- --base=/path/base-observations.jsonl --output=/path/feature-observations.jsonl --candidate-start=0 --candidate-limit=500');
const {selectCandidateShard,materializeFeatureShard}=await import('../.engine-test/auryn/v91/materialize.js');
const {AURYN_V91_OBSERVATION_VERSION}=await import('../.engine-test/auryn/v91/version.js');
const start=Math.max(0,Number(valueArg('candidate-start')||0)||0),limit=Math.max(1,Number(valueArg('candidate-limit')||500)||500);
const family=valueArg('family')||undefined,theory=valueArg('theory')||undefined;
const candidates=selectCandidateShard({start,limit,family,theory});
const base=readJsonOrJsonl(path.resolve(basePath));
const result=materializeFeatureShard(base,candidates);
const out=path.resolve(outputPath);fs.mkdirSync(path.dirname(out),{recursive:true});
const jsonl=result.observations.map(x=>JSON.stringify(x)).join('\n');fs.writeFileSync(out,jsonl+(jsonl?'\n':''));
const manifestPath=valueArg('manifest')?path.resolve(valueArg('manifest')):`${out}.manifest.json`;
const manifest={version:AURYN_V91_OBSERVATION_VERSION,candidateStart:start,candidateLimit:limit,candidateIds:candidates.map(x=>x.id),...result.manifest,partialCatalogShard:true};
fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({version:AURYN_V91_OBSERVATION_VERSION,state:'FEATURE_SHARD_COMPLETE',output:out,manifest:manifestPath,candidates:candidates.length,observations:result.observations.length,partialCatalogShard:true,note:'Run research:v9 on this shard for research evidence. A shard is not a full-catalog false-discovery result.'},null,2));
