import fs from 'node:fs';import path from 'node:path';import {performance} from 'node:perf_hooks';
const base=String(process.env.AURYN_BASE_URL||'').replace(/\/$/,'');if(!base){console.error('AURYN_BASE_URL is required');process.exit(2)}
const token=String(process.env.AURYN_AUDIT_TOKEN||'');const headers=token?{Authorization:`Bearer ${token}`}:{ };
const limit=Math.max(1,Math.min(500,Number((process.argv.find(x=>x.startsWith('--limit='))||'').split('=')[1]||30)));
const golden=['SPY','QQQ','IWM','AAPL','MSFT','NVDA','IREN','BE','ASTS','SAP','MU','NBIS','SKHY'];
const req=async route=>{const t=performance.now();const r=await fetch(base+route,{headers,cache:'no-store'});let j={};try{j=await r.json()}catch{}return{ok:r.ok,status:r.status,json:j,ms:performance.now()-t}};
const u=await req(`/api/audit/universe?limit=${Math.max(limit,30)}`);const universe=Array.isArray(u.json?.symbols)?u.json.symbols.map(x=>String(x).toUpperCase()):[];
const symbols=[...new Set([...golden,...universe])].slice(0,limit);const batch=await req(`/api/canonical?symbols=${encodeURIComponent(symbols.join(','))}`);const bm=new Map((batch.json?.items||[]).map(x=>[x?.security?.symbol,x]));
const rows=[];let critical=0,warnings=0;const lat=[];
for(const symbol of symbols){const r=await req(`/api/canonical/${encodeURIComponent(symbol)}`);lat.push(r.ms);const issues=[];if(!r.ok)issues.push(`critical: canonical endpoint ${r.status}`);const x=r.json||{},b=bm.get(symbol);if(x?.contract!=='AURYN_V9_3_5_CANONICAL_SNAPSHOT')issues.push('critical: canonical contract missing');if(String(x?.security?.symbol||'')!==symbol)issues.push('critical: security identity mismatch');if(x?.market?.displayPrice!=null&&!(Number(x.market.displayPrice)>0))issues.push('critical: non-positive display price');if(b&&b.snapshotId!==x.snapshotId)issues.push('warning: single/batch snapshot id changed during audit window');if(b?.research?.action!==x?.research?.action)issues.push('critical: single/batch action mismatch');if(b?.research?.decisionSnapshotId!==x?.research?.decisionSnapshotId)issues.push('critical: single/batch decision snapshot mismatch');const ci=issues.filter(i=>i.startsWith('critical:')).length;critical+=ci;warnings+=issues.length-ci;rows.push({symbol,status:ci?'CRITICAL':issues.length?'WARN':'PASS',latencyMs:Math.round(r.ms),snapshotId:x?.snapshotId||null,marketSnapshotId:x?.market?.snapshotId||null,decisionSnapshotId:x?.research?.decisionSnapshotId||null,action:x?.research?.action||null,researchState:x?.research?.state||null,degraded:Boolean(x?.degraded),issues});console.log(`${symbol}: ${ci?'CRITICAL':issues.length?'WARN':'PASS'} · ${Math.round(r.ms)}ms${issues.length?' · '+issues.join(' | '):''}`)}
const sorted=[...lat].sort((a,b)=>a-b),pct=p=>sorted.length?Math.round(sorted[Math.min(sorted.length-1,Math.floor((sorted.length-1)*p))]):null;const report={version:'auryn-v9.3.5',kind:'CANONICAL_SNAPSHOT_LIVE_AUDIT',baseUrl:base,generatedAt:new Date().toISOString(),total:rows.length,status:critical?'FAIL':'PASS',critical,warnings,latency:{p50:pct(.5),p95:pct(.95),p99:pct(.99),batchMs:Math.round(batch.ms)},rows};const file=process.env.AURYN_AUDIT_REPORT||path.join('artifacts',`v935-live-${new Date().toISOString().replace(/[:.]/g,'-')}.json`);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(critical)process.exitCode=1;
