import fs from 'node:fs';import path from 'node:path';
const valueArg=n=>{const p=`--${n}=`;const a=process.argv.find(x=>x.startsWith(p));return a?a.slice(p.length):''};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const startDate=valueArg('start-date'),endDate=valueArg('end-date'),symbolsPath=valueArg('symbols'),outputPath=valueArg('output');
const benchmark=String(valueArg('benchmark')||'SPY').toUpperCase();const tdKey=process.env.TWELVE_DATA_API_KEY||'';const secUA=process.env.SEC_USER_AGENT||'';const skipSec=process.argv.includes('--skip-sec');
if(!startDate||!endDate||!symbolsPath||!outputPath)throw new Error('Usage: npm run backfill:v92 -- --symbols=/path/security-master.json --start-date=2016-01-01 --end-date=2026-09-08 --output=/path/replay.json [--benchmark=SPY] [--universe=/path/universe.json]');
if(!tdKey)throw new Error('TWELVE_DATA_API_KEY is required for V9.2 historical price backfill.');if(!skipSec&&!secUA)throw new Error('SEC_USER_AGENT is required for SEC historical facts (example: YourApp contact@example.com). Use --skip-sec only when deliberately omitting fundamentals.');
const {buildTwelveDataDailyUrl,normalizeTwelveDataDaily}=await import('../.engine-test/auryn/v92/twelve-data.js');
const {normalizeAndDeriveSecCompanyFacts}=await import('../.engine-test/auryn/v92/sec-companyfacts.js');const {assembleHistoricalReplayBundle}=await import('../.engine-test/auryn/v92/assemble.js');const {auditV92ReplayBundle}=await import('../.engine-test/auryn/v92/integrity.js');
const rawMaster=JSON.parse(fs.readFileSync(path.resolve(symbolsPath),'utf8'));const securities=(Array.isArray(rawMaster)?rawMaster:rawMaster.securities||[]).map(x=>({...x,symbol:String(x.symbol||'').toUpperCase()})).filter(x=>x.symbol);
if(!securities.length)throw new Error('Security master contains no symbols.');
const delayMs=Math.max(0,Number(valueArg('delay-ms')||process.env.AURYN_V92_TD_DELAY_MS||800));const secDelay=Math.max(100,Number(process.env.AURYN_V92_SEC_DELAY_MS||150));
async function fetchJson(url,{headers={},attempts=3,timeout=30000}={}){let last;for(let i=0;i<attempts;i++){try{const r=await fetch(url,{headers,signal:AbortSignal.timeout(timeout)});if(r.status===429||r.status===503){const ra=Number(r.headers.get('retry-after'));await sleep(Number.isFinite(ra)&&ra>0?ra*1000:Math.min(60000,1500*2**i));continue;}const j=await r.json();if(!r.ok)throw new Error(j?.message||`${r.status} ${r.statusText}`);return j;}catch(e){last=e;if(i<attempts-1)await sleep(Math.min(10000,1000*2**i));}}throw last;}
async function secTickerMap(){const j=await fetchJson('https://www.sec.gov/files/company_tickers.json',{headers:{'User-Agent':secUA,'Accept-Encoding':'gzip, deflate'},timeout:20000});const m=new Map();for(const x of Object.values(j||{}))if(x?.ticker&&x?.cik_str)m.set(String(x.ticker).toUpperCase(),Number(x.cik_str));return m;}
const allSymbols=[...new Set([...securities.map(x=>x.symbol),benchmark])];const dailyBars=[];let benchmarkBars=[];const coverageGaps=[];
for(let i=0;i<allSymbols.length;i++){const symbol=allSymbols[i];try{const url=buildTwelveDataDailyUrl({symbol,startDate,endDate,apiKey:tdKey});const j=await fetchJson(url,{attempts:4,timeout:45000});const n=normalizeTwelveDataDaily(symbol,j);if(symbol===benchmark)benchmarkBars=n.bars;else dailyBars.push(...n.bars);console.error(`[prices ${i+1}/${allSymbols.length}] ${symbol}: ${n.bars.length} bars`);}catch(e){coverageGaps.push({symbol,source:'TWELVE_DATA',error:String(e?.message||e)});console.error(`[prices ${i+1}/${allSymbols.length}] ${symbol}: GAP ${String(e?.message||e)}`);}if(delayMs)await sleep(delayMs);}
if(!benchmarkBars.length)throw new Error(`Benchmark ${benchmark} could not be backfilled; research labels cannot be constructed.`);
const facts=[];if(!skipSec){const map=await secTickerMap();for(let i=0;i<securities.length;i++){const sec=securities[i],cik=Number(sec.cik||map.get(sec.symbol));if(!Number.isFinite(cik)){coverageGaps.push({symbol:sec.symbol,source:'SEC',error:'CIK unavailable'});continue;}try{const u=`https://data.sec.gov/api/xbrl/companyfacts/CIK${String(cik).padStart(10,'0')}.json`;const j=await fetchJson(u,{headers:{'User-Agent':secUA,'Accept-Encoding':'gzip, deflate'},attempts:3,timeout:30000});const n=normalizeAndDeriveSecCompanyFacts(sec.symbol,j);facts.push(...n.all);console.error(`[sec ${i+1}/${securities.length}] ${sec.symbol}: ${n.all.length} facts/derived metrics`);}catch(e){coverageGaps.push({symbol:sec.symbol,source:'SEC',error:String(e?.message||e)});console.error(`[sec ${i+1}/${securities.length}] ${sec.symbol}: GAP ${String(e?.message||e)}`);}await sleep(secDelay);}}
let universe={};const universePath=valueArg('universe');if(universePath)universe=JSON.parse(fs.readFileSync(path.resolve(universePath),'utf8'));
const bundle=assembleHistoricalReplayBundle({datasetId:valueArg('dataset-id')||`auryn-v92-${startDate}-${endDate}`,version:'1',source:skipSec?'TWELVE_DATA':'TWELVE_DATA+SEC',benchmarkSymbol:benchmark,generatedAt:new Date().toISOString(),securities,dailyBars,benchmarkBars,facts,events:Array.isArray(universe.events)?universe.events:[],universeSnapshots:Array.isArray(universe.universeSnapshots)?universe.universeSnapshots:[],pointInTimeUniverse:universe.pointInTimeUniverse===true,includesDelisted:universe.includesDelisted===true,delistingReturnsHandled:universe.delistingReturnsHandled===true});
const report=auditV92ReplayBundle(bundle);const out=path.resolve(outputPath);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(bundle,null,2)+'\n');fs.writeFileSync(`${out}.v92-audit.json`,JSON.stringify({...report,coverageGaps},null,2)+'\n');
console.log(JSON.stringify({version:report.version,state:'BACKFILL_COMPLETE',output:out,status:report.status,quality:report.quality,coverage:report.coverage,coverageGaps:coverageGaps.length,note:'Backfill output is research-only. Production CIO weights and broker permissions are unchanged.'},null,2));if(report.status==='BLOCKED')process.exitCode=1;
