"use client";
import {useCallback,useEffect,useMemo,useState} from "react";import AuthGuard from "@/components/AuthGuard";import AppShell from "@/components/AppShell";import {supabaseBrowser} from "@/lib/supabase";import Link from "next/link";import {useSearchParams} from "next/navigation";import {Trash2,Pencil,Check,X,Sparkles,ShieldCheck,Search} from "lucide-react";
function PortfolioContent(){const sp=useSearchParams(),[rows,setRows]=useState<any[]>([]),[quotes,setQuotes]=useState<any>({}),[symbol,setSymbol]=useState(sp.get("symbol")||""),[shares,setShares]=useState(""),[cost,setCost]=useState(""),[horizon,setHorizon]=useState("long"),[msg,setMsg]=useState(""),[edit,setEdit]=useState<any>(null);
 const load=useCallback(async()=>{const s=supabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user)return;const{data,error}=await s.from("portfolio_positions").select("*").eq("user_id",user.id).order("updated_at",{ascending:false});if(error){setMsg("Run supabase/v12_upgrade.sql once to enable Portfolio.");return}setRows(data||[]);const syms=(data||[]).map((x:any)=>x.symbol).slice(0,30);if(syms.length){const q=await fetch(`/api/scan?symbols=${encodeURIComponent(syms.join(","))}`).then(r=>r.json()).catch(()=>({items:[]}));setQuotes(Object.fromEntries((q.items||[]).map((x:any)=>[x.symbol,x])))}else setQuotes({})},[]);
 useEffect(()=>{load()},[load]);
 async function add(e:React.FormEvent){e.preventDefault();const s=supabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from("portfolio_positions").upsert({user_id:user.id,symbol:symbol.trim().toUpperCase(),shares:+shares,avg_cost:+cost,horizon,updated_at:new Date().toISOString()},{onConflict:"user_id,symbol"});if(error){setMsg(error.message);return}setSymbol("");setShares("");setCost("");setMsg("Position saved");load()}
 async function remove(x:any){if(!confirm(`Delete ${x.symbol} from your portfolio?`))return;const s=supabaseBrowser();const{error}=await s.from("portfolio_positions").delete().eq("id",x.id);if(error){setMsg(error.message);return}setRows(v=>v.filter(r=>r.id!==x.id));setMsg(`${x.symbol} removed`)}
 async function saveEdit(){if(!edit)return;const s=supabaseBrowser();const{error}=await s.from("portfolio_positions").update({shares:+edit.shares,avg_cost:+edit.avg_cost,horizon:edit.horizon,updated_at:new Date().toISOString()}).eq("id",edit.id);if(error){setMsg(error.message);return}setEdit(null);setMsg("Position updated");load()}
 const totals=useMemo(()=>rows.reduce((a:any,x:any)=>{const q=quotes[x.symbol];const mv=q?q.price*x.shares:x.avg_cost*x.shares,c=x.avg_cost*x.shares,day=q?.changePct!=null?mv*(q.changePct/100)/(1+q.changePct/100):0;return{value:a.value+mv,cost:a.cost+c,day:a.day+day}}, {value:0,cost:0,day:0}),[rows,quotes]);const pnl=totals.value-totals.cost;
 const attention=rows.filter((x:any)=>{const a=String(quotes[x.symbol]?.action||"");return a.includes("EXIT")||a.includes("AVOID")||a.includes("WAIT")||a.includes("CHASE")}).length;
 const healthy=Math.max(0,rows.length-attention); const health=rows.length?Math.max(35,Math.min(92,Math.round(82-attention*9))):0;
 return <section className="portfolioPage v41Portfolio">
   <div className="v41PortfolioHead"><div><div className="eyebrow">PORTFOLIO INTELLIGENCE</div><h1>Your money, interpreted.</h1><p>Broker apps show what you own. NIVORA highlights what may deserve action, what can wait, and where new risk should be questioned.</p></div><Link href="/dashboard">Open Radar →</Link></div>
   <div className="v41PortfolioHero"><div><small>PORTFOLIO VALUE</small><b>${totals.value.toLocaleString(undefined,{maximumFractionDigits:0})}</b><span className={totals.day>=0?"good":"bad"}>{totals.day>=0?"+":""}${totals.day.toLocaleString(undefined,{maximumFractionDigits:0})} today</span></div><div className="v41Health"><small>NIVORA PORTFOLIO HEALTH</small><b>{rows.length?health:"—"}<em>{rows.length?"/100":""}</em></b><span>{attention?`${attention} position${attention>1?"s":""} deserve attention`:(rows.length?"No urgent decision flags":"Add positions to start")}</span></div><div className="v41PortfolioCounts"><span><b>{healthy}</b> stable / hold</span><span><b>{attention}</b> attention</span><span><b>{rows.length}</b> tracked</span></div></div>
   <div className="v41AddPosition"><div><Search size={18}/><div><b>Add a position</b><span>Search by ticker, then add shares and average cost.</span></div></div><form className="positionForm" onSubmit={add}><input placeholder="Ticker" value={symbol} onChange={e=>setSymbol(e.target.value)} required/><input placeholder="Shares" type="number" step="any" value={shares} onChange={e=>setShares(e.target.value)} required/><input placeholder="Average cost" type="number" step="0.01" value={cost} onChange={e=>setCost(e.target.value)} required/><select value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="short">Short term</option><option value="swing">Swing</option><option value="long">Long term</option></select><button>Track</button></form></div>{msg&&<div className="portfolioMsg">{msg}</div>}
   <div className="v41ActionTitle"><div><Sparkles size={18}/><div><small>ACTION CENTER</small><h2>What deserves attention?</h2></div></div><span>Research signals, not trade instructions.</span></div>
   <div className="v41PositionList">{rows.length?rows.map((x:any)=>{const q=quotes[x.symbol],ret=q?((q.price/x.avg_cost)-1)*100:null,isEdit=edit?.id===x.id;const action=String(q?.action||"HOLD / REVIEW");const levels=q?.levels||{};return <article className="v41Position" key={x.id}>{isEdit?<div className="positionEdit"><b>{x.symbol}</b><input type="number" step="any" value={edit.shares} onChange={e=>setEdit({...edit,shares:e.target.value})}/><input type="number" step="0.01" value={edit.avg_cost} onChange={e=>setEdit({...edit,avg_cost:e.target.value})}/><select value={edit.horizon} onChange={e=>setEdit({...edit,horizon:e.target.value})}><option value="short">Short term</option><option value="swing">Swing</option><option value="long">Long term</option></select><button onClick={saveEdit}><Check size={16}/></button><button onClick={()=>setEdit(null)}><X size={16}/></button></div>:<><Link className="v41PositionMain" href={`/stock/${encodeURIComponent(x.symbol)}`}><div className="v41PosTicker"><b>{x.symbol}</b><span>{x.shares} shares · avg ${Number(x.avg_cost).toFixed(2)}</span></div><div className="v41PosAction"><small>NIVORA</small><b className={action.includes("BUY")?"good":action.includes("EXIT")||action.includes("AVOID")?"bad":"mid"}>{action}</b><span>{q?.reason||"Open the position for the full decision thesis."}</span></div><div className="v41PosPlan"><span><small>NOW</small><b>{q?`$${q.price}`:"—"}</b></span><span><small>BETTER ENTRY</small><b>{levels.entryLow&&levels.entryHigh?`$${levels.entryLow}–$${levels.entryHigh}`:"Open analysis"}</b></span><span><small>RETURN</small><b className={ret!=null&&ret>=0?"good":"bad"}>{ret!=null?`${ret>=0?"+":""}${ret.toFixed(1)}%`:"—"}</b></span></div></Link><div className="rowActions"><button onClick={()=>setEdit({...x})} title="Edit position"><Pencil size={16}/></button><button className="danger" onClick={()=>remove(x)} title="Delete position"><Trash2 size={16}/></button></div></>}</article>}):<div className="emptyToday"><ShieldCheck size={22}/><b>No positions yet</b><span>Add a ticker above. NIVORA will turn your holdings into an action-focused portfolio view.</span></div>}</div>
 </section>}
export default function Page(){return <AuthGuard><AppShell><PortfolioContent/></AppShell></AuthGuard>}
