"use client";
import {useCallback,useEffect,useMemo,useState} from "react";import AuthGuard from "@/components/AuthGuard";import AppShell from "@/components/AppShell";import {supabaseBrowser} from "@/lib/supabase";import Link from "next/link";import {useSearchParams} from "next/navigation";import {Trash2,Pencil,Check,X} from "lucide-react";
function PortfolioContent(){const sp=useSearchParams(),[rows,setRows]=useState<any[]>([]),[quotes,setQuotes]=useState<any>({}),[symbol,setSymbol]=useState(sp.get("symbol")||""),[shares,setShares]=useState(""),[cost,setCost]=useState(""),[horizon,setHorizon]=useState("long"),[msg,setMsg]=useState(""),[edit,setEdit]=useState<any>(null);
 const load=useCallback(async()=>{const s=supabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user)return;const{data,error}=await s.from("portfolio_positions").select("*").eq("user_id",user.id).order("updated_at",{ascending:false});if(error){setMsg("Run supabase/v12_upgrade.sql once to enable Portfolio.");return}setRows(data||[]);const syms=(data||[]).map((x:any)=>x.symbol).slice(0,30);if(syms.length){const q=await fetch(`/api/scan?symbols=${encodeURIComponent(syms.join(","))}`).then(r=>r.json()).catch(()=>({items:[]}));setQuotes(Object.fromEntries((q.items||[]).map((x:any)=>[x.symbol,x])))}else setQuotes({})},[]);
 useEffect(()=>{load()},[load]);
 async function add(e:React.FormEvent){e.preventDefault();const s=supabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from("portfolio_positions").upsert({user_id:user.id,symbol:symbol.trim().toUpperCase(),shares:+shares,avg_cost:+cost,horizon,updated_at:new Date().toISOString()},{onConflict:"user_id,symbol"});if(error){setMsg(error.message);return}setSymbol("");setShares("");setCost("");setMsg("Position saved");load()}
 async function remove(x:any){if(!confirm(`Delete ${x.symbol} from your portfolio?`))return;const s=supabaseBrowser();const{error}=await s.from("portfolio_positions").delete().eq("id",x.id);if(error){setMsg(error.message);return}setRows(v=>v.filter(r=>r.id!==x.id));setMsg(`${x.symbol} removed`)}
 async function saveEdit(){if(!edit)return;const s=supabaseBrowser();const{error}=await s.from("portfolio_positions").update({shares:+edit.shares,avg_cost:+edit.avg_cost,horizon:edit.horizon,updated_at:new Date().toISOString()}).eq("id",edit.id);if(error){setMsg(error.message);return}setEdit(null);setMsg("Position updated");load()}
 const totals=useMemo(()=>rows.reduce((a:any,x:any)=>{const q=quotes[x.symbol];const mv=q?q.price*x.shares:x.avg_cost*x.shares,c=x.avg_cost*x.shares,day=q?.changePct!=null?mv*(q.changePct/100)/(1+q.changePct/100):0;return{value:a.value+mv,cost:a.cost+c,day:a.day+day}}, {value:0,cost:0,day:0}),[rows,quotes]);const pnl=totals.value-totals.cost;
 return <section className="portfolioPage"><div className="eyebrow">POSITIONS</div><h1>Your portfolio</h1><p>Track positions, cost basis and horizon so NIVORA can evaluate what you own—not just whether a stock is buyable.</p><div className="portfolioSummary four"><div><small>MARKET VALUE</small><b>${totals.value.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div><small>COST BASIS</small><b>${totals.cost.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div><small>TOTAL P/L</small><b className={pnl>=0?"good":"bad"}>{pnl>=0?"+":""}${pnl.toLocaleString(undefined,{maximumFractionDigits:0})} · {totals.cost?`${((totals.value/totals.cost-1)*100).toFixed(1)}%`:"—"}</b></div><div><small>TODAY</small><b className={totals.day>=0?"good":"bad"}>{totals.day>=0?"+":""}${totals.day.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div></div>
 <form className="positionForm" onSubmit={add}><input placeholder="Ticker" value={symbol} onChange={e=>setSymbol(e.target.value)} required/><input placeholder="Shares" type="number" step="any" value={shares} onChange={e=>setShares(e.target.value)} required/><input placeholder="Average cost" type="number" step="0.01" value={cost} onChange={e=>setCost(e.target.value)} required/><select value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="short">Short term</option><option value="swing">Swing</option><option value="long">Long term</option></select><button>Track position</button></form>{msg&&<div className="portfolioMsg">{msg}</div>}
 <div className="positionList">{rows.length?rows.map((x:any)=>{const q=quotes[x.symbol],ret=q?((q.price/x.avg_cost)-1)*100:null,isEdit=edit?.id===x.id;return <div className="positionRow" key={x.id}>{isEdit?<div className="positionEdit"><b>{x.symbol}</b><input type="number" step="any" value={edit.shares} onChange={e=>setEdit({...edit,shares:e.target.value})}/><input type="number" step="0.01" value={edit.avg_cost} onChange={e=>setEdit({...edit,avg_cost:e.target.value})}/><select value={edit.horizon} onChange={e=>setEdit({...edit,horizon:e.target.value})}><option value="short">Short term</option><option value="swing">Swing</option><option value="long">Long term</option></select><button onClick={saveEdit}><Check size={16}/></button><button onClick={()=>setEdit(null)}><X size={16}/></button></div>:<><Link className="positionMain" href={`/stock/${encodeURIComponent(x.symbol)}`}><div><b>{x.symbol}</b><span>{x.shares} shares · avg ${Number(x.avg_cost).toFixed(2)} · {x.horizon}</span></div><div>{q&&<><strong>${q.price}</strong><small className={ret!=null&&ret>=0?"good":"bad"}>{ret!=null?`${ret>=0?"+":""}${ret.toFixed(1)}%`:""}</small></>}</div></Link><div className="rowActions"><button onClick={()=>setEdit({...x})} title="Edit position"><Pencil size={16}/></button><button className="danger" onClick={()=>remove(x)} title="Delete position"><Trash2 size={16}/></button></div></>}</div>}):<div className="emptyToday">No positions yet.</div>}</div></section>}
export default function Page(){return <AuthGuard><AppShell><PortfolioContent/></AppShell></AuthGuard>}
