"use client";
import Link from "next/link";
import {Bitcoin,Banknote,WalletCards,Pencil,Trash2,ArrowRight,Check,X} from "lucide-react";

export default function HoldingsIntelligence({assets,onEdit,onRemove,editingId,editDraft,onEditDraft,onSaveEdit,onCancelEdit,pendingDelete,onConfirmRemove,onCancelRemove}:{assets:any[];onEdit?:(x:any)=>void;onRemove?:(x:any)=>void;editingId?:string|number|null;editDraft?:any;onEditDraft?:(x:any)=>void;onSaveEdit?:()=>void;onCancelEdit?:()=>void;pendingDelete?:string|number|null;onConfirmRemove?:()=>void;onCancelRemove?:()=>void}){
 const rows=(assets||[]).map(x=>{const cash=x.assetType==="CASH",value=cash?Number(x.amount||0):Number(x.quantity||0)*Number(x.price||0);return{...x,value}}).sort((a,b)=>b.value-a.value);
 const total=rows.reduce((n,x)=>n+x.value,0);
 return <section id="portfolio-holdings" className="aurynSection"><div className="holdingsIntelHead"><div><div className="aurynEyebrow">Positions</div><h2>Your holdings</h2></div><span>{rows.length} tracked assets</span></div>
  <div className="aurynHoldingsList">{rows.map((x:any)=>{const cash=x.assetType==="CASH",crypto=x.assetType==="CRYPTO",name=cash?(x.currency||x.symbol||"USD"):x.symbol,weight=total?x.value/total*100:0,pnl=!cash&&Number(x.avgCost)>0?(Number(x.price)-Number(x.avgCost))*Number(x.quantity):null,action=cash?"LIQUIDITY":String(x.action||"REVIEW").replaceAll("_"," "),source=x.source||x,isEditing=editingId!=null&&String(source.id)===String(editingId),isDeleting=pendingDelete!=null&&String(source.id)===String(pendingDelete);return <div className={`aurynHoldingGroup ${isEditing||isDeleting?"active":""}`} key={`${x.assetType}-${name}`}>
   <article className="aurynHoldingRow">
    <div className="aurynHoldingName">{cash?<Banknote size={18}/>:crypto?<Bitcoin size={18}/>:<WalletCards size={18}/>}<div><b>{name}</b><span>{cash?"Cash":crypto?"Crypto":"Stock"} · {weight.toFixed(1)}% of portfolio</span></div></div>
    <div className="aurynHoldingMetric"><small>VALUE</small><b>${x.value.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div>
    <div className="aurynHoldingMetric"><small>RETURN</small><b className={pnl!=null&&pnl<0?"bad":"good"}>{cash?"—":pnl==null?"—":`${pnl>=0?"+":""}$${Math.abs(pnl).toLocaleString(undefined,{maximumFractionDigits:0})}`}</b></div>
    <div className="aurynHoldingMetric"><small>AURYN</small><b>{action}</b></div>{!cash?<div className="aurynHoldingFacts"><span><small>SHARES</small><b>{Number(x.quantity||0).toLocaleString(undefined,{maximumFractionDigits:4})}</b></span><span><small>AVG COST</small><b>${Number(x.avgCost||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</b></span></div>:<div className="aurynHoldingFacts"><span><small>AMOUNT</small><b>${x.value.toLocaleString(undefined,{maximumFractionDigits:0})}</b></span></div>}
    <div className="aurynHoldingActions">{!cash&&<Link href={`/stock/${encodeURIComponent(name)}`} aria-label={`Open ${name} decision`} title="Open research"><ArrowRight size={16}/></Link>}{onEdit&&<button type="button" aria-label={`Edit ${name}`} title="Edit position" onClick={()=>onEdit(source)}><Pencil size={15}/></button>}{onRemove&&<button type="button" aria-label={`Delete ${name}`} title="Delete position" onClick={()=>onRemove(source)}><Trash2 size={15}/></button>}</div>
   </article>
   {isEditing&&editDraft?<div className="aurynHoldingEditRow"><div><small>EDIT POSITION</small><b>{name}</b></div><label><span>{cash?"Amount":"Quantity"}</span><input aria-label="Quantity" type="number" step="any" value={editDraft.shares} onChange={e=>onEditDraft?.({...editDraft,shares:e.target.value})}/></label>{!cash?<label><span>Average cost</span><input aria-label="Average cost" type="number" step="0.01" value={editDraft.avg_cost} onChange={e=>onEditDraft?.({...editDraft,avg_cost:e.target.value})}/></label>:<span/>}<div className="aurynInlineActions"><button className="primary" type="button" onClick={onSaveEdit}><Check size={15}/> Save</button><button type="button" onClick={onCancelEdit}><X size={15}/> Cancel</button></div></div>:null}
   {isDeleting?<div className="aurynDeleteConfirm"><div><small>REMOVE POSITION?</small><b>Delete {name} from this portfolio?</b><span>This removes the tracked position; it does not place a broker order.</span></div><div className="aurynInlineActions"><button className="danger" type="button" onClick={onConfirmRemove}><Trash2 size={15}/> Delete</button><button type="button" onClick={onCancelRemove}><X size={15}/> Keep</button></div></div>:null}
  </div>})}</div>
 </section>
}