"use client";
import MetricInfo from "@/components/v65/MetricInfo";
export default function PortfolioHealth({pulse}:{pulse:any}){
 const score=Number(pulse?.health?.score||0),top3=Number(pulse?.concentration?.top3Pct||0),largest=Number(pulse?.concentration?.largestPositionPct||0),cash=Number(pulse?.allocations?.cashPct||0),crypto=Number(pulse?.allocations?.cryptoPct||0);
 const actions=pulse?.actions||[],weak=actions.filter((x:any)=>["WATCH","TRIM_RISK","AVOID"].includes(x.portfolioAction)).slice(0,2),add=actions.find((x:any)=>x.portfolioAction==="ADD");
 const strengths=[cash>=5&&cash<=25?`Cash flexibility is ${cash}%`:"",largest<=18?`Largest position is contained at ${largest}%`:"",add?`${add.symbol} has constructive company evidence and portfolio fit`:""].filter(Boolean);
 const drags=[largest>18?`Largest position is ${largest}% — single-name concentration is elevated`:"",top3>45?`Top 3 holdings are ${top3}% of portfolio value`:"",crypto>20?`Crypto exposure is ${crypto}% and raises volatility pressure`:"",...weak.map((x:any)=>`${x.symbol}: ${x.reason}`)].filter(Boolean).slice(0,3);
 const improve=[largest>18?"Reduce future additions to oversized positions; rebalance only when thesis, tax and risk/reward support it.":"Keep single-position sizing disciplined.",top3>45?"Direct new capital toward high-quality, lower-correlated opportunities rather than reinforcing the same cluster.":"Maintain diversification as new capital is deployed.",weak.length?"Reassess holdings whose company evidence or portfolio fit has weakened.":"No weak holding requires an immediate portfolio change."];
 return <section className="portfolioHealthPanel portfolioGlass"><header><div><small>PORTFOLIO HEALTH <MetricInfo title="Portfolio Health" description="A diagnostic of concentration, diversification, liquidity and holding evidence. It is not a return forecast or a reason to trade by itself."/></small><h2><b>{score}</b><span>/100 · {pulse?.health?.label||"CURRENT"}</span></h2></div><p>Health measures how well the portfolio is constructed for taking risk—not whether every holding will go up.</p></header><div className="healthExplainGrid"><article><small>Why this score</small><b>{strengths[0]||"Current holding quality and portfolio structure provide a workable base."}</b>{strengths.slice(1).map(x=><span key={x}>{x}</span>)}</article><article><small>Holding it back</small><b>{drags[0]||"No major structural weakness is dominating the score."}</b>{drags.slice(1).map(x=><span key={x}>{x}</span>)}</article><article><small>Improve portfolio</small><b>{improve[0]}</b><span>{improve[1]}</span><span>{improve[2]}</span></article><article><small>Goal fit</small><b>Use Health with return, drawdown and your target—not in isolation.</b><span>Higher Health can improve portfolio resilience, but NIVORA will not fabricate a probability of reaching your financial goal without a defined target, contributions and horizon.</span></article></div><footer>Do not trade just to raise this score. Changes should improve expected risk/reward and fit your goal first.</footer></section>
}