"use client";
import {useMemo,useState} from "react";
import {calculatePortfolioPeriod,type PortfolioPeriod} from "@/lib/v65/portfolio";
import {useRouter} from "next/navigation";
import PortfolioPerformanceChart from "./PortfolioPerformanceChart";
// PortfolioHealth methodology is intentionally surfaced through the compact Health popover in V9.9.9.2.
const PERIODS=["1D","1W","1M","3M","6M","YTD","1Y","ALL"] as const;
const money=(n:number)=>`$${Math.abs(n).toLocaleString(undefined,{maximumFractionDigits:0})}`;
export default function PortfolioPulse({pulse,risk}:{pulse:any;risk?:any}){
 const router=useRouter(); const[period,setPeriod]=useState<(typeof PERIODS)[number]>("1M"),[healthOpen,setHealthOpen]=useState(false),[matrixHover,setMatrixHover]=useState<any>(null);
 const requested=useMemo(()=>calculatePortfolioPeriod(pulse?.history?.points||[],period as PortfolioPeriod),[pulse,period]),available=useMemo(()=>calculatePortfolioPeriod(pulse?.history?.points||[],"ALL" as PortfolioPeriod),[pulse]);
 const r=requested?.status==="ACTUAL"?requested:available?.status==="ACTUAL"?{...available,period,partial:true}:requested,points=Array.isArray(r?.points)?r.points:[],actual=r?.status==="ACTUAL";
 const total=Number(pulse?.totalValue||0),cash=Number(pulse?.cashValue||0),drivers=[...(pulse?.drivers||[])],totalPnl=drivers.reduce((a:number,x:any)=>a+Number(x.pnl||0),0),invested=Math.max(0,total-cash),cost=Math.max(0,invested-totalPnl),positions=drivers.length;
 const history=pulse?.history?.points||[],last=history.at?.(-1),prev=history.length>1?history[history.length-2]:null,todayPnl=last&&prev?Number(last.totalValue||0)-Number(prev.totalValue||0):0,todayPct=prev?.totalValue?todayPnl/Number(prev.totalValue)*100:null;
 const health=Number(pulse?.health?.score||0),largest=Number(pulse?.concentration?.largestPositionPct||0),top3=Number(pulse?.concentration?.top3Pct||0),top5=Number(pulse?.concentration?.top5Pct||0),cashPct=Number(pulse?.allocations?.cashPct||0),cryptoPct=Number(pulse?.allocations?.cryptoPct||0),stockPct=Number(pulse?.allocations?.equityPct||0);
 const actions=[...(pulse?.actions||[])].filter((x:any)=>x.portfolioAction&&x.portfolioAction!=="HOLD"),attention=actions.filter((x:any)=>/AVOID|TRIM|WATCH/i.test(x.portfolioAction)).sort((a:any,b:any)=>Number(b.weightPct||0)-Number(a.weightPct||0)).slice(0,5);
 const gainers=drivers.filter((x:any)=>Number(x.pnl)>0).sort((a:any,b:any)=>Number(b.pnl)-Number(a.pnl)).slice(0,5),losers=drivers.filter((x:any)=>Number(x.pnl)<0).sort((a:any,b:any)=>Number(a.pnl)-Number(b.pnl)).slice(0,5),driverMax=Math.max(1,...drivers.map((x:any)=>Math.abs(Number(x.pnl||0))));
 const opportunityRows=drivers.filter((x:any)=>Number.isFinite(Number(x.opportunityScore))),opportunityCoverage=positions?opportunityRows.length/positions:0,mapRows=opportunityCoverage>=.45?opportunityRows:drivers;
 const tracked=history[0]?.asOf,ret=actual?Number(r.portfolioReturnPct):null,alphaSpy=actual?Number(r.alphaVsSpyPct):null,alphaQqq=actual?Number(r.alphaVsQqqPct):null;
 const allocTotal=Math.max(1,stockPct+cryptoPct+cashPct),stockDeg=stockPct/allocTotal*360,cryptoDeg=cryptoPct/allocTotal*360;
 return <section className="aurynPortfolioCockpit aurynPremiumPortfolio">
  <section className="aurynPremiumHero"><div><small>PORTFOLIO</small><h1>{money(total)}</h1><b className={todayPnl<0?"bad":"good"}>{todayPnl>=0?"+":"-"}{money(todayPnl)} {todayPct==null?"":`· ${todayPct>=0?"+":""}${todayPct.toFixed(2)}%`} <em>today</em></b></div><div className="aurynPremiumMetrics">
   <article><small>TODAY P/L</small><b className={todayPnl<0?"bad":"good"}>{todayPnl>=0?"+":"-"}{money(todayPnl)}</b></article><article><small>TOTAL P/L</small><b className={totalPnl<0?"bad":"good"}>{totalPnl>=0?"+":"-"}{money(totalPnl)}</b></article><article><small>INVESTED</small><b>{money(invested)}</b></article><article><small>CASH</small><b>{money(cash)}</b><span>{cashPct.toFixed(1)}%</span></article><article><small>POSITIONS</small><b>{positions}</b></article><article className="health" onClick={()=>setHealthOpen(v=>!v)}><small>HEALTH</small><b>{health}/100</b><span>{pulse?.health?.label||"Current"} · details</span></article>
  </div>{healthOpen?<div className="aurynHealthPopover"><b>Portfolio health · {health}/100</b><span>Cash buffer {cashPct.toFixed(1)}% · largest position {largest.toFixed(1)}% · top 3 {top3.toFixed(1)}%.</span><small>Use this with return, drawdown and your goals—not as a standalone trade signal.</small></div>:null}</section>

  <section className="aurynPremiumCard aurynPerformanceCard"><header><div><small>PERFORMANCE</small><h2>Portfolio Performance</h2></div><span>{tracked?`Tracked since ${new Date(tracked).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}`:"Tracking begins with your first exact snapshot"}</span></header><nav className="aurynPortfolioPeriods">{PERIODS.map(x=><button key={x} className={period===x?"on":""} onClick={()=>setPeriod(x)}>{x}</button>)}</nav>
   {actual&&points.length>=2?<PortfolioPerformanceChart points={points}/>:<div className="aurynHistoryNotice"><b>Performance history is building.</b><span>AURYN will never fabricate portfolio history.</span></div>}
   <div className="aurynPerformanceSummary"><span><small>PORTFOLIO RETURN</small><b>{ret==null?"N/A":`${ret>=0?"+":""}${ret.toFixed(2)}%`}</b></span><span><small>DOLLAR CHANGE</small><b>{actual&&r.start&&r.end?`${Number(r.end.totalValue)-Number(r.start.totalValue)>=0?"+":"-"}${money(Number(r.end.totalValue)-Number(r.start.totalValue))}`:"N/A"}</b></span><span><small>VS SPY</small><b>{alphaSpy==null?"N/A":`${alphaSpy>=0?"+":""}${alphaSpy.toFixed(2)}%`}</b></span><span><small>VS QQQ</small><b>{alphaQqq==null?"N/A":`${alphaQqq>=0?"+":""}${alphaQqq.toFixed(2)}%`}</b></span></div><div className="aurynInsightRibbon"><article className="aurynInsightTile gain"><small>TOP CONTRIBUTOR</small><b>{gainers[0]?.symbol||"—"}</b><span>{gainers[0]?`+${money(Number(gainers[0].pnl||0))}`:"Building"}</span></article><article className="aurynInsightTile drag"><small>BIGGEST DRAG</small><b>{losers[0]?.symbol||"—"}</b><span>{losers[0]?`-${money(Number(losers[0].pnl||0))}`:"None"}</span></article><article className="aurynInsightTile"><small>CASH BUFFER</small><b>{cashPct.toFixed(1)}%</b><span>{cashPct>=10?"Flexible":cashPct>=5?"Moderate":"Tight"}</span></article><article className="aurynInsightTile"><small>CONCENTRATION</small><b>{largest.toFixed(1)}%</b><span>Largest position</span></article><article className="aurynInsightTile gauge"><small>RISK CAPACITY</small><div className="aurynRiskGauge" style={{"--gauge":`${Math.max(5,Math.min(95,health))}%`} as any}><i/></div><b>{health}/100</b></article></div>
  </section>

  <section className="aurynPremiumGrid">
   <article className="aurynPremiumCard aurynDriverCard"><header><div><small>CONTRIBUTION</small><h2>Portfolio Drivers</h2></div><span>Dollar impact on your capital</span></header><div className="aurynContributionColumns"><div><b>Top gainers</b>{gainers.map((x:any)=><div key={x.symbol} className="aurynInteractiveDriver" role="link" tabIndex={0} onClick={()=>router.push(`/stock/${encodeURIComponent(x.symbol)}`)}><strong>{x.symbol}</strong><i><em className="pos" style={{width:`${Math.max(4,Math.abs(Number(x.pnl))/driverMax*100)}%`}}/></i><span className="good">+{money(Number(x.pnl))}</span></div>)}</div><div><b>Top drags</b>{losers.map((x:any)=><div key={x.symbol} className="aurynInteractiveDriver" role="link" tabIndex={0} onClick={()=>router.push(`/stock/${encodeURIComponent(x.symbol)}`)}><strong>{x.symbol}</strong><i><em className="neg" style={{width:`${Math.max(4,Math.abs(Number(x.pnl))/driverMax*100)}%`}}/></i><span className="bad">-{money(Number(x.pnl))}</span></div>)}</div></div><div className="aurynContributionBar" aria-hidden="true"/>
   </article>
   <article className="aurynPremiumCard aurynAllocationCard"><header><div><small>STRUCTURE</small><h2>Allocation & Risk</h2></div></header><div className="aurynAllocationBody"><div className="aurynAllocationDonut" style={{background:`conic-gradient(var(--auryn-green,#28765c) 0 ${stockDeg}deg,var(--auryn-gold,#bc8737) ${stockDeg}deg ${stockDeg+cryptoDeg}deg,var(--auryn-muted,#d8d2c7) ${stockDeg+cryptoDeg}deg 360deg)`}}><span><b>{money(total)}</b><small>Total</small></span></div><div className="aurynAllocationLegend"><span><i className="stocks"/>Stocks <b>{stockPct.toFixed(1)}%</b></span><span><i className="crypto"/>Crypto <b>{cryptoPct.toFixed(1)}%</b></span><span><i className="cash"/>Cash <b>{cashPct.toFixed(1)}%</b></span></div><div className="aurynConcentrationBars"><span>Largest position <b>{largest.toFixed(1)}%</b><i><em style={{width:`${largest}%`}}/></i></span><span>Top 3 positions <b>{top3.toFixed(1)}%</b><i><em style={{width:`${top3}%`}}/></i></span><span>Top 5 positions <b>{top5.toFixed(1)}%</b><i><em style={{width:`${top5}%`}}/></i></span></div></div></article>
  </section>

  <section className="aurynPremiumGrid">
   <article className="aurynPremiumCard aurynMatrixCard"><header><div><small>CAPITAL</small><h2>{opportunityCoverage>=.45?"Portfolio Opportunity Map":"Position Matrix"}</h2></div><span>{opportunityCoverage>=.45?"AURYN opportunity × portfolio weight":"Portfolio weight × current P/L"}</span></header><div className="aurynMatrixLabels"><span>{opportunityCoverage>=.45?"Higher opportunity":"Positive P/L"}</span><span>Higher weight →</span></div><div className="aurynMatrixPlot">{mapRows.slice(0,14).map((x:any)=>{const weight=Math.min(92,Math.max(7,Number(x.weightPct||0)*5)),vertical=opportunityCoverage>=.45?Math.min(90,Math.max(10,Number(x.opportunityScore||50))):Math.min(90,Math.max(10,50+Number(x.pnl||0)/driverMax*38));return <i key={x.symbol} style={{left:`${weight}%`,bottom:`${vertical}%`}} className={`aurynInteractiveMatrix ${Number(x.pnl||0)<0?"loss":"gain"}`} onMouseEnter={()=>setMatrixHover(x)} onMouseLeave={()=>setMatrixHover(null)} onClick={()=>router.push(`/stock/${encodeURIComponent(x.symbol)}`)}><b>{x.symbol}</b></i>})}{matrixHover?<div className="aurynMatrixTooltip"><b>{matrixHover.symbol}</b><span>Weight {Number(matrixHover.weightPct||0).toFixed(1)}%</span><span>P/L {Number(matrixHover.pnl||0)>=0?"+":""}{money(Number(matrixHover.pnl||0))}</span><small>Click to open Research →</small></div>:null}</div></article>
   <article className="aurynPremiumCard aurynNeedsCard"><header><div><small>DECISIONS</small><h2>What needs attention?</h2></div><span>{attention.length} prioritized</span></header>{attention.length?attention.map((x:any,i:number)=><div key={x.symbol}><i>{i+1}</i><span><b>{x.symbol}</b><em>{String(x.portfolioAction).replaceAll("_"," ")}</em><small>{Number(x.weightPct||0).toFixed(1)}% weight</small></span><p>{x.reason}</p><strong>{x.nextTrigger||"Wait for new decision-grade evidence"}</strong></div>):<p className="empty">No portfolio action requires immediate attention.</p>}</article>
  </section>
 </section>
}