create table if not exists public.nivora_validation_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  engine_version text not null,
  mode text not null,
  price numeric not null,
  score integer not null,
  confidence integer not null,
  action text,
  thesis_label text,
  factors jsonb not null default '{}'::jsonb,
  levels jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  audit_id text,
  observed_at timestamptz not null default now(),
  return_1d numeric,
  return_5d numeric,
  return_20d numeric,
  return_60d numeric,
  return_120d numeric,
  max_drawdown_60d numeric,
  max_favorable_60d numeric
);
create index if not exists nivora_validation_symbol_time_idx on public.nivora_validation_snapshots(symbol,observed_at desc);
create index if not exists nivora_validation_engine_idx on public.nivora_validation_snapshots(engine_version,score,mode);
alter table public.nivora_validation_snapshots enable row level security;
-- No public policies: writes/reads are server-side only through the service role.
