create table if not exists public.nivora_decision_history (
  id bigint generated by default as identity primary key,
  symbol text not null,
  observed_at timestamptz not null default now(),
  price numeric,
  company_score int,
  growth_score int,
  financial_score int,
  analyst_score int,
  valuation_score int,
  thesis_score int,
  opportunity_score int,
  evidence_confidence int,
  thesis_label text,
  thesis_state text,
  action text,
  horizon_3m int,
  horizon_6m int,
  horizon_1y int,
  horizon_2y int,
  horizon_3y int,
  reason text,
  main_risk text,
  source_snapshot jsonb default '{}'::jsonb
);
create index if not exists nivora_decision_history_symbol_time_idx on public.nivora_decision_history(symbol, observed_at desc);
create index if not exists nivora_decision_history_time_idx on public.nivora_decision_history(observed_at desc);

alter table public.nivora_investment_scan add column if not exists horizon_3m int;
alter table public.nivora_investment_scan add column if not exists horizon_6m int;
alter table public.nivora_investment_scan add column if not exists horizon_1y int;
alter table public.nivora_investment_scan add column if not exists horizon_2y int;
alter table public.nivora_investment_scan add column if not exists horizon_3y int;
alter table public.nivora_investment_scan add column if not exists priority_source text;

create table if not exists public.nivora_decision_outcomes (
  id bigint generated by default as identity primary key,
  history_id bigint not null references public.nivora_decision_history(id) on delete cascade,
  symbol text not null,
  horizon_days int not null,
  evaluated_at timestamptz not null default now(),
  start_price numeric not null,
  end_price numeric not null,
  return_pct numeric not null,
  unique(history_id,horizon_days)
);
create index if not exists nivora_decision_outcomes_symbol_idx on public.nivora_decision_outcomes(symbol,horizon_days);
