-- NIVORA V59: immutable decision snapshots + Arena outcomes + reliability buckets
create table if not exists public.nivora_v59_decision_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  observed_at timestamptz not null,
  price numeric not null,
  engine_version text not null,
  weights_version text not null,
  valuation_version text not null,
  today_policy_version text not null,
  evidence_fingerprint text not null,
  benchmark_symbol text not null default 'SPY',
  sector_benchmark_symbol text,
  decision jsonb not null,
  evidence jsonb not null,
  created_at timestamptz not null default now(),
  unique(symbol, observed_at, engine_version, evidence_fingerprint)
);
create index if not exists nivora_v59_snapshots_lookup on public.nivora_v59_decision_snapshots(engine_version,symbol,observed_at desc);

create table if not exists public.nivora_v59_arena_outcomes (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null references public.nivora_v59_decision_snapshots(id) on delete cascade,
  horizon text not null check (horizon in ('30D','90D','180D','1Y','2Y')),
  outcome_at timestamptz not null,
  end_price numeric not null,
  raw_return_pct numeric not null,
  benchmark_return_pct numeric,
  alpha_pct numeric,
  sector_return_pct numeric,
  sector_alpha_pct numeric,
  max_drawdown_pct numeric,
  hit boolean,
  created_at timestamptz not null default now(),
  unique(snapshot_id,horizon)
);
create index if not exists nivora_v59_arena_engine_horizon on public.nivora_v59_arena_outcomes(horizon,snapshot_id);

create table if not exists public.nivora_v59_reliability_buckets (
  id bigint generated by default as identity primary key,
  engine_version text not null,
  weights_version text not null,
  horizon text not null,
  archetype text not null default 'unknown',
  score_bucket text not null,
  sample_n integer not null,
  hit_rate_pct numeric,
  avg_alpha_pct numeric,
  reliability_score numeric,
  status text not null check (status in ('COLLECTING','CALIBRATED')),
  calculated_at timestamptz not null default now(),
  unique(engine_version,weights_version,horizon,archetype,score_bucket)
);

alter table public.nivora_v59_decision_snapshots enable row level security;
alter table public.nivora_v59_arena_outcomes enable row level security;
alter table public.nivora_v59_reliability_buckets enable row level security;
