create table if not exists public.nivora_model_registry(
 version text primary key,
 status text not null default 'shadow',
 notes text,
 created_at timestamptz not null default now(),
 promoted_at timestamptz
);
insert into public.nivora_model_registry(version,status,notes)
values('NIVORA V30','shadow','9.5 architecture release: regime, quality, audit and validation foundation')
on conflict(version) do nothing;

create table if not exists public.nivora_provider_health(
 id bigint generated by default as identity primary key,
 provider text not null,
 capability text not null,
 ok boolean not null,
 latency_ms integer,
 error_code text,
 checked_at timestamptz not null default now()
);
create index if not exists nivora_provider_health_idx on public.nivora_provider_health(provider,capability,checked_at desc);
alter table public.nivora_model_registry enable row level security;
alter table public.nivora_provider_health enable row level security;
